### ISSUE TITLE
Multi image tracking - Augmented Images

### ISSUE THREAD

**Issue by AlexandruStrujac** [google-ar/arcore-unity-sdk#324] opened 2018-07-24 03:27 UTC
Hello. Is there a way to make multi image tracking in one scene? Now I can track only one image. Sorry I am a beginner and I need help. Thank you.

**Comment by pablisho** [comment] 2018-07-24 17:46
Hi, Augmented Images examples shows how to track more than one image. What is the behaviour that you are experiencing or what is preventing you to track more than one image?

**Comment by AlexandruStrujac** [comment] 2018-07-24 17:48
I dont know how to assign objects to each image. Sorry but i am a beginner. I created an Image Data Base with 3 images, but i dont know how to asign objects to each image.

**Comment by AlexandruStrujac** [comment] 2018-07-24 17:54
All i have done is to augment an object to all images. But if i have 3 objects how i can assign object 1 to image 1, object 2 to image 2, and so on....

**Comment by pablisho** [comment] 2018-07-24 18:13
Hi, I think you can use either AugmentedImage.DatabaseIndex or AugmentedImage.Name to identify the images and then assign the object/prefab to that you want to each of them. Does that help?

**Comment by AlexandruStrujac** [comment] 2018-07-24 18:23
Yes. But I don't know how to do it. I am stupid beginner. Can you help me? Just a line for one image and one object.  Please.

**Comment by AlexandruStrujac** [comment] 2018-07-24 18:38
😐 no. Sorry. Thank you for your time.

**Comment by AlexandruStrujac** [comment] 2018-07-24 18:56
Yes my project is based on ArCore example

**Comment by pablisho** [comment] 2018-07-25 21:30
Hi, I think this is a duplicate of #253. Take a look at that issue and see if the information there helps you. Feel free to comment if you have more questions.

**Closed by pablisho** 2018-07-25 21:30 UTC
