### ISSUE TITLE
ARCore plane anchor changes suddenly

### ISSUE THREAD

**Issue by deadmarston** [google-ar/arcore-unity-sdk#127] opened 2018-03-01 12:38 UTC
I print the arcore plane information to see how plane works, however I found that the plane information is someway strange. 
dataformat: anchor.position.x anchor.position.y anchor.position.z anchor.eulerangle.y anchor.extent.x anchor.extent.z
data1,frame1: 1.049368  -1.467689  0.764016 280.592200 2.086480  4.775109
data1,frame2: 0.698588  -1.467811  0.645530 340.823800 4.298982  3.513837

data2,frame1: -0.342749  -0.687885  0.967416 359.748400 1.670383  0.969965
data2,frame2: -0.340775  -0.687890  0.967310 270.158500 0.971888  1.670243

**Comment by pablisho** [comment] 2018-03-01 19:50
What do you find strange in that information? The ExtentX and ExtentY are related to the plane orientation, so if a new better estimate changed the plane orientation (as you see it in eulerangle.y) it's reasonable that extent.x and extent.y will change too.
The position of the plane can also be updated but a new estimate, because it represents the center of plane. If the new estimate extended the plane in only one direction it's reasonable that the plane position will change.
For a better representation of the plane (non rectangular) you can use the polygon instead of the extents as they are used in [TrackedPlaneVisualizer.cs](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/Examples/HelloAR/Scripts/TrackedPlaneVisualizer.cs#L120)

**Comment by pablisho** [comment] 2018-03-10 01:50
I'm closing this because I believe it's the expected behavior. Please feel free to reopen if you get more evidence that this is a bug.

**Closed by pablisho** 2018-03-10 01:50 UTC
