### ISSUE TITLE
EntryPointNotFoundException: ArPrestoAugmentedImageDatabase_create

### ISSUE THREAD

**Issue by luxcreativity** [google-ar/arcore-unity-sdk#407] opened 2018-10-01 16:09 UTC
Getting this error in Unity 2018.2.10f1 in an empty project

EntryPointNotFoundException: ArPrestoAugmentedImageDatabase_create
GoogleARCoreInternal.AugmentedImageDatabaseApi.CreateArPrestoAugmentedImageDatabase (System.Byte[] rawData) (at Assets/GoogleARCore/SDK/Scripts/Api/AugmentedImageDatabaseApi.cs:59)
GoogleARCore.AugmentedImageDatabase.get_m_ArPrestoDatabaseHandle () (at Assets/GoogleARCore/SDK/Scripts/AugmentedImageDatabase.cs:104)
GoogleARCoreInternal.ApiPrestoConfig..ctor (GoogleARCore.ARCoreSessionConfig config) (at Assets/GoogleARCore/SDK/Scripts/Api/ApiPrestoConfig.cs:73)
GoogleARCoreInternal.ARCoreAndroidLifecycleManager._SetConfiguration (GoogleARCore.ARCoreSessionConfig config) (at Assets/GoogleARCore/SDK/Scripts/Managers/ARCoreAndroidLifecycleManager.cs:278)
GoogleARCoreInternal.ARCoreAndroidLifecycleManager._OnEarlyUpdate () (at Assets/GoogleARCore/SDK/Scripts/Managers/ARCoreAndroidLifecycleManager.cs:176)
GoogleARCoreInternal.ARPrestoCallbackManager._EarlyUpdateTrampoline () (at Assets/GoogleARCore/SDK/Scripts/Managers/ARPrestoCallbackManager.cs:151)
(wrapper native-to-managed) GoogleARCoreInternal.ARPrestoCallbackManager:_EarlyUpdateTrampoline ()
GoogleARCoreInternal.InstantPreviewManager+<UpdateLoop>c__Iterator1.MoveNext () (at Assets/GoogleARCore/SDK/InstantPreview/Scripts/InstantPreviewManager.cs:286)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

**Comment by buffalovision** [comment] 2018-10-03 03:47
Also having this issue in a blank project using 2018.1.8f1.

**Comment by pablisho** [comment] 2018-10-03 13:32
Hi, thanks for the report. Does this happen on device or using InstantPreview?

**Comment by pablisho** [comment] 2018-10-03 13:42
I think this is actually a dup of #403

**Comment by luxcreativity** [comment] 2018-10-03 16:37
Hi @pablisho I don't think so, this happens when importing the AR Core Package into the scene, not on play/Instant Preview.

To replicate:

Create New Project

Import most recent AR Core Pacakge into Unity

Receive error

**Comment by pablisho** [comment] 2018-10-03 16:41
Try change your project platform to Android, I believe that should fix it.

**Comment by buffalovision** [comment] 2018-10-03 18:17
This happens when running instant preview using the example scene for augmented images.

**Comment by fredsa** [comment] 2018-10-04 18:42
Duplicate of #403

**Closed by fredsa** 2018-10-04 18:42 UTC
