### ISSUE TITLE
Rotation Only Mode

### ISSUE THREAD

**Issue by sam598** [google-ar/arcore-unity-sdk#282] opened 2018-06-28 18:46 UTC
Would it be possible to have a 3DOF "rotation only" mode in ARCore? ARKit has an option for it (https://developer.apple.com/documentation/arkit/arorientationtrackingconfiguration?language=objc) and it's great for experiences where there is low light or features. For example a stargazing app.

Something like this can be achieved by just ignoring the position data provided by ARCore, but if you were to point an ARCore device up at the sky or a blank wall camera tracking freezes, instead of still tracking rotation.

This could also be achieved using the camera API and the device's gyroscope, but it would be missing the accurate camera intrinsics and solid timestamp synchronization between motion and image.

**Comment by pablisho** [comment] 2018-06-29 15:09
Hi, if you want rotation only, try changing the TrackedPoseDriver TrackingType from "Rotation and Position" to "Rotation Only". The tracked pose driver is in the FirstPersonCamera in ARCoreDevice. Let me know if this helps.

**Comment by sam598** [comment] 2018-06-29 18:12
Thanks pablisho!

As I understand it setting TrackedPoseDriver to "Rotation Only" only prevents position data from being applied to the attached object, it doesn't change anything about the XR API behaves behind the scenes.

So ARCore is still tracking the device's position, it's just not being applied to the camera in the scene. If you were to point an ARCore device up at the sky or a blank wall camera tracking freezes, instead of only tracking rotation from the gyroscope.

It's a niche use case, but still useful in some areas and would give ARCore better parity with other AR SDKs that support orientation only modes.

**Comment by pablisho** [comment] 2018-07-18 23:58
Hi, ARCore uses visual features to estimate both position and orientation. If you point it to a white wall you'll probably get the Tracking state to become LostTracking or NotTracking.
I'm closing this as this is the current expected behaviour of ARCore. Feel free to reopen or open a new issue if you have more questions.

**Comment by sam598** [comment] 2018-07-19 00:51
Hi,

This is a request for a feature that's common in other AR SDKs like ARKit and Vuforia, but is missing from ARCore. If it's not possible to have 3DOF as a manual option, can ARCore fallback to 3DOF rotation only like Tango used to do?

I cannot reopen this repo as I am not a collaborator.

**Comment by pablisho** [comment] 2018-07-19 01:04
Sure, I can take it as a feature request.

**Comment by sam598** [comment] 2018-07-19 02:29
Thanks, appreciated!

**Comment by fredsa** [comment] 2018-09-17 23:19
Hi @sam598. We don't have any plans to provide a rotation only mode.

However, you could try creating a script that:
1. When TrackingState is Tracking: copies the rotation from the Tracked Pose Driver's transform
2. When TrackingState is not Tracking: use Unity's `Input.gyro` to determine orientation

Note, #2 is needed, because tracking pose provided by #1 stops updating when tracking pauses. Tracking is paused when, for example, the camera is temporarily covered.

**Closed by fredsa** 2018-09-17 23:19 UTC
Labels: feature request

**Comment by Augmentaio** [comment] 2020-04-29 09:37
Hi, are there any plans to implement this in one of the future updates? I am especially interested in a hybrid mode where ARCore uses visual features if possible but if trackinglost then it estimates using the other sensors and back again if visual features come into view again
