### ISSUE TITLE
Ar core Insta Preview dont work on Note 9

### ISSUE THREAD

**Issue by Edgar-BlipparDev** [google-ar/arcore-unity-sdk#427] opened 2018-10-22 14:02 UTC
Ar core insta preview does not work on note 9 even when it is supported device for Arcore. Insta Preview launches but Unity Camera stays black..

In the ARCore Instant Preview app I can see "Press PLAY in Unity editor to stream", but after hitting the play button the screens turns black -> after 1 or 2 seconds it switches back to die initial app screen.

**Comment by pablisho** [comment] 2018-10-26 20:15
Hi, thanks for the report. I added it to our internal tracker.

**Comment by fredsa** [comment] 2019-01-11 01:05
Duplicate of #484

**Closed by fredsa** 2019-01-11 01:05 UTC
Labels: Instant Preview, bug, fixed in upcoming release
