### ISSUE TITLE
Camera background does not get redrawn if there is an object with a negative scale within frame and there is a directional light with shadows enabled

### ISSUE THREAD

**Issue by dive155** [google-ar/arcore-unity-sdk#356] opened 2018-08-16 23:01 UTC
This bug had been halting my project for a few days, but I've finally hunted it down.

**Steps to reproduce:**
1) Create a new empty project
2) Import ARCore 1.4 unitypackage
3) Create a new empty scene
4) Place ARCoreDevice prefab onto the scene
5) Add a directional light onto the scene
6) Set it's shadow settings to either **Soft Shadows** or **Hard Shadows**
7) Create a new 3D object (i.e. a plane)
8) Set its scale to a negative value **on a single axis**
9) Start the play mode or build the app onto a device
10) Watch the background glitching out when the plane is within frame (see attached images) 

It happens with both Instant Preview and in the actual build.
Tested using **ARCore 1.4** with **Unity 2018.1.2** on Huawei P20.

Note: The bug does not occur when shadows are set to No Shadows
Note: The bug does not occur if the object's material uses Unlit shaders

I've added a couple more objects onto my test scene so it's more clear what's going on
**The scene as it is supposed to look:**
![bug1](https://user-images.githubusercontent.com/11758962/44238681-798de280-a1be-11e8-94c4-a324fb1ca6ea.JPG)

**The same scene after I've changed the plane's scale to (-1, 1, 1):**
![bug2](https://user-images.githubusercontent.com/11758962/44238739-ab9f4480-a1be-11e8-997c-10d1287ced72.JPG)

I hope it helps :)
Good luck!

**Comment by pablisho** [comment] 2018-08-23 14:42
Hi, thanks for the detailed report. I believe this is a duplicate of #258.

**Closed by pablisho** 2018-08-23 14:42 UTC
