### ISSUE TITLE
CheckApkAvailability throws ArPresto Error

### ISSUE THREAD

**Issue by adri21112** [google-ar/arcore-unity-sdk#393] opened 2018-09-18 11:02 UTC
Hi.
I am working in a code to detect te availability of android devices to run AR Core.

This is my Code:
`

	// Use this for initialization
	void Start () {
		Debug.Log("TVRLP::Start");
		StartCoroutine(CheckCompatibility());
	}
	
	// Update is called once per frame
	private IEnumerator CheckCompatibility()
	{
		Debug.Log("TVRLP::StartCoroutine");
		GoogleARCore.AsyncTask<GoogleARCore.ApkAvailabilityStatus> checkTask = GoogleARCore.Session.CheckApkAvailability();
		CustomYieldInstruction customYield = checkTask.WaitForCompletion();
		yield return customYield;
		Debug.Log("TVRLP::FinishCoroutine");
		GoogleARCore.ApkAvailabilityStatus result = checkTask.Result;
		switch (result)
		{
			case ApkAvailabilityStatus.SupportedApkTooOld:
			Debug.Log("TVRLP::Supported apk too old");
			break;
			case ApkAvailabilityStatus.SupportedInstalled:
			Debug.Log("TVRLP::Supported and installed");
			break;
			case ApkAvailabilityStatus.SupportedNotInstalled:
			Debug.Log("TVRLP::Supported, not installed, requesting installation");
			Session.RequestApkInstallation(false);
			break;
			case ApkAvailabilityStatus.UnknownChecking:
			Debug.Log("TVRLP::Unknown Checking");
			break;
			case ApkAvailabilityStatus.UnknownError:
			Debug.Log("TVRLP::Unknown Error");
			break;
			case ApkAvailabilityStatus.UnknownTimedOut:
			Debug.Log("TVRLP::Unknown Timed out");
			break;
			case ApkAvailabilityStatus.UnsupportedDeviceNotCapable:
			Debug.Log("TVRLP::Unsupported Device Not Capable");
			break;
		}
	}
   

`

When I create a build the console doesn't show errors,  the apk is deployed to the devices without problems.

When I run the APP the code after `yield return` not is executed and the Android Console throws this:
![image](https://user-images.githubusercontent.com/8613412/45683121-d6c0df00-bb42-11e8-91b4-9e4239be7369.png)

Can you help me?
My test devices are Huawei P9 and Motorola G6

Thanks for your attention.

**Comment by small-potatoes** [comment] 2018-09-21 21:46
Hi @adri21112 , is this happening in instant preview or on device?

**Comment by fredsa** [comment] 2018-10-04 18:45
Marking this as a duplicate of #241.

**Closed by fredsa** 2018-10-04 18:45 UTC
