### ISSUE TITLE
SDK locks up the camera until rebooting device when device is hot

### ISSUE THREAD

**Issue by NLferdiNL** [google-ar/arcore-unity-sdk#191] opened 2018-05-02 12:32 UTC
I've had this happen on two phones so far.
Both of them are Galaxy S7s. One is my personal phone from T-Mobile NL. (With their stuff added like a bootscreen and such) and the other is factory standard one. After starting my apps a couple times for testing it eventually locks the Camera away until I restart the device.

So far I have not seen any errors happening prior to this and everything functions as normal until something just clicks and locks the camera. After that no app including the camera app that comes with the phone is able to use any of the cameras on the device.

**Comment by pablisho** [comment] 2018-05-03 17:58
Hi, thanks for the report. Which version of ARCore are you using? Do you have repro steps? Could you attach a logcat of when the issue happens?

@inio are you aware of this being reported as a platform level?

**Comment by inio** [comment] 2018-05-04 01:03
This sounds similar to google-ar/arcore-android-sdk/issues/242

We've seen this in a couple cases and it's usually related to the device experiencing thermal extremes (either currently or since reboot).  It's likely a driver issue and there's little to nothing we can do about it.

**Comment by Dezec** [comment] 2018-05-04 08:44
I too have the same issue happen quite frequently on my S7 Edge. Only solution is a restart. Using the latest (1.1) version of ARCore and Unity. As far as I am aware, there is no way to reproduce it as it's random. 

Opening the default camera application during this problem gives you the error "Camera Failed"

**Comment by inio** [comment] 2018-05-04 17:47
@Dezec Would you say that it tends to start when the device is very hot?

**Comment by NLferdiNL** [comment] 2018-05-04 18:37
I can test this again next Tuesday. I will try to report and document as much as possible.

**Comment by NLferdiNL** [comment] 2018-05-16 07:28
To follow up on the comment I deleted, I haven't gotten to it yet due to other things needing my attention. When I did get time to check it didn't happen but I didn't push it thoroughly.

**Comment by Dezec** [comment] 2018-05-16 07:45
Hey, Sorry for the late reply. I too haven't gotten to test this anymore as the project I was working on is currently paused. 

But if I remember correctly, it didn't only happen when the device was hot. Maybe a bit warm.

**Comment by chaosemer** [comment] 2018-09-17 23:47
Closing this to collapse tracking into [#242](https://github.com/google-ar/arcore-android-sdk/issues/242).

**Closed by chaosemer** 2018-09-17 23:47 UTC
Labels: known issue
