### ISSUE TITLE
Instantiate object in scene but can't force it to an fixed position

### ISSUE THREAD

**Issue by lluma** [google-ar/arcore-unity-sdk#193] opened 2018-05-07 02:33 UTC
I am now using some fixed position to instantiate my objects in the scene and attach them to the anchors to let ARcore to track them. But the result I got was that the objects cannot stand still at the fixed position, they move along with my camera. Why does that happen?

Below is a short film of my result
https://drive.google.com/open?id=19c1_Axk8yicGNWXA5e-N290tWwzY4hvR

Why my objects are not fixed like the Andy is?
Here is how I instantiate my objects and attach to the new anchor I create ( ignore the 'bias' in my code ) 
note:
-- vertex is the object's each vertex.
-- wall is a cube object
```
            wall.ForEach((vertex) =>
            {
                if (count % 8 == 0)
                    verticesText.GetComponent<Text>().text += "\n" + vertex.ToString();
                else
                    verticesText.GetComponent<Text>().text += vertex.ToString();
                myAnchor = Instantiate(MyWallAnchorPrefab, vertex + bias, Quaternion.identity);
                if (count % 8 == 0)
                {
                    anchorPosition /= 8;
                    anchor = Session.CreateAnchor(new Pose(anchorPosition, Quaternion.identity));
                    anchorPosition = Vector3.zero;
                }
                anchorPosition += vertex;
                count++;
                if (anchor != null)
                    myAnchor.transform.parent = anchor.transform;
            });
```
Is there anyone that encountered the same problem ?

**Comment by lluma** [comment] 2018-05-07 06:04
I solve it. Just the objects are too far away from origin and I can't reach it due to the obstacle.

**Comment by ping-xiong** [comment] 2018-05-08 03:02
I have a similar problem. But the models are closed to me.

If the model is too big, it can't force it to an fixed position.
You can see on a  short film below.
https://drive.google.com/open?id=1c-ZlJVRpUrHbePxui8OxX7Gw-TUbWEGI

But if the model is small, it's OK.
Another short film:
https://drive.google.com/open?id=14eYZI0Kjk0Rk_oxxq6diztCZtKoMG9Qu

Why does that happen?

**Comment by lluma** [comment] 2018-05-15 06:32
@ping-xiong  I think just that our model is too huge and we can't reach the position of the specified model component. If we move the model close toward us, then the problem may be solved!

**Comment by pablisho** [comment] 2018-05-24 01:12
Hi @ping-xiong, sorry for the late reply, and thanks for the videos.
I think the problem is not the model being too big, it's a problem of where your model origin is defined. When you click on a plane the hit test returns a position on the plane, if you use that pose to set your model's position, and your model origin is in the center of the object, then half of your model will be below the plane and half above creating a bad AR experience. What you want is to place the bottom of your object on the plane, not the center. I think you have the same issue in both videos, but if the model is small the difference is not that noticeable. Let me know if this helps.

**Comment by pablisho** [comment] 2018-06-04 20:37
Hi, I'm closing this because I believe your question is solved. Feel free to reopen if you still experience issues about this.

**Closed by pablisho** 2018-06-04 20:37 UTC
