### ISSUE TITLE
Texture mirrored right-left

### ISSUE THREAD

**Issue by filipsladek** [google-ar/arcore-unity-sdk#111] opened 2018-02-25 06:06 UTC
`ExternApi.TextureReader_acquireFrame` returns textures  right-left mirrored.
Is it intended?

**Comment by pablisho** [comment] 2018-02-28 03:20
Thanks for the bug report. I added it to our internal tracking, we'll be checking if this is intended behaviour or not.

**Comment by filipsladek** [comment] 2018-02-28 03:46
What I would like to emphasise is that on display it shows the camera feed right, but when I get texture and work with that or save it to jpg file, it is mirrored. So either there is some reason I do not see or it should not be like that.

**Comment by harrywangwork** [comment] 2018-02-28 19:02
The image is not mirrored, but actually 90 degree rotated. Since the camera sensor is 90-rotated to the screen on your device(and most other mobile devices), the image orientation is not what you see from the display. 
BTW, what was the device orientation when you captured the image?

**Comment by pablisho** [comment] 2018-03-06 22:16
I'm closing this as we believe is intended behaviour. Please reopen if you have issues.

**Closed by pablisho** 2018-03-06 22:16 UTC
Labels: bug

**Comment by cstensonpv** [comment] 2018-03-27 07:06
Hi! How can it be intended to mirror the image? Please explain. As an example detecting written text is quite hard with current methods or yes I can blit the texture to get it correct however seems like an unnecessary operation and not something I would like to do frequently.
