### ISSUE TITLE
Crash on ARCore 1.0, Unity 2017.3.1f1, Pixel XL, Android 8.0.0

### ISSUE THREAD

**Issue by lingllting** [google-ar/arcore-unity-sdk#121] opened 2018-02-28 10:51 UTC

**Comment by lingllting** [comment] 2018-02-28 11:26
02-28 19:19:14.398 12566-20539/? E/Unity: Tango service connected but Tango client library not loaded. Tango service unavailable.
                                           
                                          (Filename:  Line: 114)
02-28 19:25:12.535 22079-22094/? E/Unity: Unable to find unitygar
02-28 19:25:15.223 22079-22094/? E/Unity: Could not create an ARCore session.
02-28 19:25:15.236 22079-22094/? E/Unity: ARCore failed to create a session.
                                           
                                          (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-28 19:25:15.248 22079-22094/? E/Unity: Could not create an ARCore session.  The current Unity Editor may not support this version of ARCore.
                                              at GoogleARCore.ARCoreSession.Awake()
                                           
                                          (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by lingllting** [comment] 2018-02-28 11:28
02-28 19:19:14.398 12566-20539/? E/Unity: Tango service connected but Tango client library not loaded. Tango service unavailable.
                                           
                                          (Filename:  Line: 114)
02-28 19:25:12.535 22079-22094/? E/Unity: Unable to find unitygar
02-28 19:25:15.223 22079-22094/? E/Unity: Could not create an ARCore session.
02-28 19:25:15.236 22079-22094/? E/Unity: ARCore failed to create a session.
                                           
                                          (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)
02-28 19:25:15.248 22079-22094/? E/Unity: Could not create an ARCore session.  The current Unity Editor may not support this version of ARCore.
                                              at GoogleARCore.ARCoreSession.Awake()
                                           
                                          (Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

**Comment by pablisho** [comment] 2018-02-28 17:56
@inio Do you know if Pixel XL also has this issue? https://github.com/google-ar/arcore-android-sdk/issues/198

**Comment by inio** [comment] 2018-02-28 18:20
@pablisho Don't think it's that - Pixel devices are fully supported on 8.

**Comment by lingllting** [comment] 2018-03-01 05:26
@inio I forgot to merge the origin branch into my local branch and got the old version, but when I ran with the latest version, I got new error list as follows:
03-01 11:46:14.025 661-661/? E/VibratorService: Setting amplitude  to: 1856
03-01 11:46:14.032 744-754/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
03-01 11:46:14.032 744-754/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
03-01 11:46:16.580 29283-29298/? E/Unity: Unable to find unitygar
03-01 11:46:16.647 744-754/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
03-01 11:46:16.648 744-754/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
03-01 11:46:19.201 29283-29298/? E/Unity: Unable to find instant_preview_unity_plugin
03-01 11:46:19.309 29283-29283/? E/ARCore-IS: Play Store install service could not be bound.
03-01 11:46:26.278 2308-29158/? E/NowController: Failed to access data from EntryProvider.
                                                 java.util.concurrent.TimeoutException: Waited 20 seconds for com.google.common.util.concurrent.q@8ddddc3[status=PENDING]
                                                     at com.google.common.util.concurrent.d.get(SourceFile:57)
                                                     at com.google.common.util.concurrent.l.get(SourceFile:2)
                                                     at com.google.android.apps.gsa.staticplugins.nowstream.b.a.ar.btU(SourceFile:20)
                                                     at com.google.android.apps.gsa.staticplugins.nowstream.b.a.ar.btT(SourceFile:139)
                                                     at com.google.android.apps.gsa.staticplugins.nowstream.b.a.au.run(Unknown Source:2)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.as.run(SourceFile:4)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.h.run(Unknown Source:4)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.ap.run(SourceFile:4)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.ap.run(SourceFile:4)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                     at java.lang.Thread.run(Thread.java:764)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.l.run(SourceFile:6)
03-01 11:46:27.011 1953-27671/? E/ctxmgr: [BaseServerTask]Failed network request due to no network connectivity: 
03-01 11:46:27.012 1953-27671/? E/ctxmgr: [AccountAclCallback]Failed Acl fetch: network status=1
03-01 11:46:27.032 1953-27671/? E/ctxmgr: [BaseServerTask]Failed network request due to no network connectivity: 
03-01 11:46:27.033 1953-27671/? E/ctxmgr: [AccountAclCallback]Failed Acl fetch: network status=1
03-01 11:46:27.034 654-654/? E/hw-IPCThreadState: binder thread pool (1 threads) starved for 146 ms
03-01 11:46:27.921 744-754/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
03-01 11:46:27.921 744-754/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
03-01 11:46:28.123 485-485/? E/SurfaceFlinger: [com.google.ar.core.examples.unity.helloar/com.google.ar.core.InstallActivity#0] rejecting buffer: bufWidth=1462, bufHeight=910, front.active.{w=1544, h=817}
03-01 11:46:28.157 485-485/? E/SurfaceFlinger: [com.google.ar.core.examples.unity.helloar/com.google.ar.core.InstallActivity#0] rejecting buffer: bufWidth=1360, bufHeight=1026, front.active.{w=1544, h=817}
03-01 11:46:28.190 485-485/? E/SurfaceFlinger: [com.google.ar.core.examples.unity.helloar/com.google.ar.core.InstallActivity#0] rejecting buffer: bufWidth=1298, bufHeight=1096, front.active.{w=1544, h=817}
03-01 11:46:28.223 485-485/? E/SurfaceFlinger: [com.google.ar.core.examples.unity.helloar/com.google.ar.core.InstallActivity#0] rejecting buffer: bufWidth=1248, bufHeight=1153, front.active.{w=1544, h=817}
03-01 11:46:30.515 2308-29162/? E/NowController: Failed to access data from EntryProvider.
                                                 java.util.concurrent.TimeoutException: Waited 20 seconds for com.google.common.util.concurrent.q@ef894ed[status=PENDING]
                                                     at com.google.common.util.concurrent.d.get(SourceFile:57)
                                                     at com.google.common.util.concurrent.l.get(SourceFile:2)
                                                     at com.google.android.apps.gsa.staticplugins.nowstream.b.a.ar.btU(SourceFile:20)
                                                     at com.google.android.apps.gsa.staticplugins.nowstream.b.a.ar.btT(SourceFile:139)
                                                     at com.google.android.apps.gsa.staticplugins.nowstream.b.a.au.run(Unknown Source:2)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.as.run(SourceFile:4)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.h.run(Unknown Source:4)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.ap.run(SourceFile:4)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.ap.run(SourceFile:4)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                     at java.lang.Thread.run(Thread.java:764)
                                                     at com.google.android.apps.gsa.shared.util.concurrent.a.l.run(SourceFile:6)
03-01 11:46:32.796 639-978/? E/volume_listener: check_and_set_gain_dep_cal: Failed to set gain dep cal level
03-01 11:46:32.798 744-754/? E/ANDR-PERF-OPTSHANDLER: Warning: Resource [2, 0] not supported for core 1. Instead use resource for core 0
03-01 11:46:32.798 744-754/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [2, 2, 0]
03-01 11:46:32.800 29283-29298/? E/ARCore-AJA: Exception details:
                                               com.google.ar.core.exceptions.UnavailableUserDeclinedInstallationException
                                                   at com.google.ar.core.InstallActivity.onCreate(InstallActivity.java:123)
                                                   at android.app.Activity.performCreate(Activity.java:6975)
                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                   at android.os.Looper.loop(Looper.java:164)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
03-01 11:46:32.800 29283-29298/? E/ArPresto: ArPresto::Apk install failed with 0.

**Comment by inio** [comment] 2018-03-01 09:33
The error `E/ARCore-IS: Play Store install service could not be bound.` indicates that you have a very out of date Play Store app (updated in early January at the latest), or no Play Store at all.  Since this is a Pixel, that's rather surprising.

The error should have corresponded to clicking "CONTINUE" in the "This application requires the latest version of ARCore" dialog.   13.5 seconds later control returns to the application and the `UnavailableUserDeclinedInstallationException` is generated.  What happened during those 13.5 seconds?

**Comment by lingllting** [comment] 2018-03-10 06:16
@inio I clicked "CONTINUE" and it jumped to the Play Store APP, when I went back to the AR application,  It said "ARCore encountered a problem connecting, please restart the app again." and crashed.  As you know, Chinese network cannot connect to Play Store, is it a problem? Have you ever tested on Pixel devices yet?

**Comment by lingllting** [comment] 2018-03-10 06:20
@inio By the way, the ARCore SDK Preview version worked well on Pixel XL.

**Comment by inio** [comment] 2018-03-10 22:44
Unfortunately we currently don't have an official distribution channel for ARCore in China.  Stay tuned.

**Comment by lingllting** [comment] 2018-03-11 00:42
@inio，I dont mean the PlayStore connection issue，Have you ever tested the arcore v1.0 on pixel devices as it is not marked as a known issue currently？

**Comment by inio** [comment] 2018-03-22 20:39
Sorry, just noticed this languishing in my queue.

Yes, we have tested extensively across all supported devices.

**Comment by pablisho** [comment] 2018-03-29 20:37
Hi, I'm closing this as this is the expected behaviour. You need access to Play Store to download the latest ARCore apk.

**Closed by pablisho** 2018-03-29 20:37 UTC
