### ISSUE TITLE
Session.GetTrackables<TrackedPoint> not work?

### ISSUE THREAD

**Issue by henry82421** [google-ar/arcore-unity-sdk#143] opened 2018-03-16 03:45 UTC
I modified some codes in the HelloAR sample  to try to find **TrackedPoint**.
The following is what I modified in HelloController.cs. I just replaced TrackedPlane with TrackedPoint. But when I create multiple anchors, it still show the search UI and the TrackedPoint can not be found. I would like to know if someone has the same situation or I am mistaken. Thanks!

```
 private List<TrackedPlane> m_AllPlanes = new List<TrackedPlane>(); //line 67

            // Disable the snackbar UI when no planes are valid. //line 113
            Session.GetTrackables<TrackedPlane>(m_AllPlanes);
            bool showSearchingUI = true;
            for (int i = 0; i < m_AllPlanes.Count; i++)
            {
                if (m_AllPlanes[i].TrackingState == TrackingState.Tracking)
                {
                    showSearchingUI = false;
                    break;
                }
            }
```

```
private List<TrackedPoint> m_AllPlanes = new List<TrackedPoint>();

            // Disable the snackbar UI when no points are valid.
            Session.GetTrackables<TrackedPoint>(m_AllPlanes);
            bool showSearchingUI = true;
            for (int i = 0; i < m_AllPlanes.Count; i++)
            {
                if (m_AllPlanes[i].TrackingState == TrackingState.Tracking)
                {
                    showSearchingUI = false;
                    break;
                }
            }
```

**Comment by pablisho** [comment] 2018-03-16 14:58
Hi, what are you trying to obtain? If you just want to get all the feature points you should use Frame.PointCloud.
Feature points are not necessarily tracked points. Tracked points are only generated when you perform a Frame.Raycast passing Feature point flag and an anchor is placed on that feature point. So placing an anchor on a plane won't generate a TrackedPoint.

**Comment by henry82421** [comment] 2018-03-17 04:36
Hi pablisho, I want to find tracked points instead of feature points. I expect the search UI to disappear when the Andy model (created by the result returned from Frame.Raycast)  appears on my screen but it still exists.

I also tried to print out the value of **m_AllPlanes.Count** to observe, but this value is always 0 regardless of how many Andy models I put on the feature points.

Also would like to ask, `tracked points` with the definition of [`oriented points`](https://developers.google.com/ar/discover/concepts#oriented_points) is the same?
 Thanks a lot!

**Comment by pablisho** [comment] 2018-03-20 15:20
Hi, I think there may be a confusion around what TrackedPoints are and when those are added to ARCore.
If when performing the Raycast you are not doing it with either TrackableHitFlags.FeaturePoint or TrackableHitFlags.FeaturePointWithSurfaceNormal, then no TrackedPoint will be generated for that Raycast. Another way to generate a tracked point would be to call Session.CreateAnchor(pose).
The reason is Anchors must be generated on top of a Trackable which it could be a TrackedPlane or a TrackedPoint.
In HelloAR project, the Raycast is performed on planes, so the Trackable would be TrackedPlane, and no TrackedPoint will be generated for that Andy.

I'm curious, what are you trying to do that requires to get the "TrackedPoints"?

**Comment by nydej2** [comment] 2018-04-04 09:16
Hello Pablisho. You said if one wants to obtain feature points, one should use Frame.PointCloud. I am currently experimenting with this pointCloud. However, if I Print out the confidence Value for each point of the cloud (in each frame i guess), the confidence is always zero. Do you have any recommendations, how i can observe the point Cloud over a bigger time Period?

**Comment by pablisho** [comment] 2018-04-26 18:45
Closing this because it's expected behaviour. @nydej2 's issue was handled in #159

**Closed by pablisho** 2018-04-26 18:45 UTC
