### ISSUE TITLE
Instant Preview does not support Augmented Images

### ISSUE THREAD

**Issue by HolgerDurach** [google-ar/arcore-unity-sdk#403] opened 2018-09-28 13:59 UTC
I get an error message in the unity editor: 
"EntryPointNotFoundException: ArPrestoAugmentedImageDatabase_create" 
when I try to start the AugmentedImage example from the editor. The window simply stays white after that...
I also cannot find such a method in the arcore_instant_preview_unity_plugin.dll. What am I doing wrong?  

![image](https://user-images.githubusercontent.com/29951835/46212545-8a418480-c336-11e8-84cc-cce3df1994f8.png)

**Comment by HolgerDurach** [comment] 2018-09-28 14:14
other examples like "HelloAr" do work fine btw.
Also AugmentedImage works fine if I build and deploy it to my S8+. (At least with 2017.4)

**Comment by pablisho** [comment] 2018-10-03 13:44
Hi, thanks for the report. I added it to our internal tracker.

**Comment by LuisCRSousa** [comment] 2018-10-09 18:46
Have a pixel 2 XL. Problem still persists

**Comment by justinleavesley** [comment] 2018-10-15 05:04
This problem still exists in 1.5.0 ARCore unity sdk.
Unity on windows (build set to Android API target 7.0) any use of instant preview with augmented image database fails on this EntryPointNotFoundException. Works fine on the device.  The device is a Samsung Galaxy Note 9.

Is the dll on windows incorrectly built?

**Comment by 4songsoftranscendence** [comment] 2018-10-16 03:10
@HolgerDurach , How do you deploy to your s8 and test without pressing play in the unity editor?

Also having the same issue with my s8+.

**Comment by justinleavesley** [comment] 2018-10-16 07:16
> @HolgerDurach , How do you deploy to your s8 and test without pressing play in the unity editor?
> 
> Also having the same issue with my s8+.

You can select Build and Run from the file menu. This will deploy to your connected device. You will need to ensure that your build settings have been switched to Android (goto Build Settings).

**Comment by 4songsoftranscendence** [comment] 2018-10-16 12:06
@justinsleavesly so  I've beeb doing and it pops up on the screen with the usual pre play loading screen, but the second play is pressed on unity, it breaks due to the error noted at the top of the thread. I was wondering if there's another way to press play once its on the android,  kind of like testing it without instant preview.

**Comment by SpaceWarpStudio** [comment] 2018-10-23 11:10
Can confirm I'm also receiving this error when trying to use preview mode for the AugmentedImages example on a Galaxy Tab S4. Builds and runs on the device without a problem. ARCore v1.5.180910096, arcore-unity-sdk-v1.5.0, Unity 2018.2.13f1

**Comment by chaosemer** [comment] 2018-11-21 17:19
Instant Preview does not support Augmented Images yet. We're going to make this more clear in an upcoming release.

**Comment by FUBAR2077** [comment] 2018-12-05 10:03
Maybe fix it rather than make it more clear that it doesn't work? ;D

**Comment by TheBricktop** [comment] 2018-12-09 19:36
Same thing but works with the example database, but after i've created my custom one it get the error again.

**Comment by ThatChocolateGuy** [comment] 2018-12-17 21:09
So odd that this used to work just fine in previous builds, but now it won't??

**Comment by fredsa** [comment] 2019-01-10 22:58
Duplicate of #484

**Closed by fredsa** 2019-01-10 22:58 UTC
Labels: Instant Preview, duplicate, feature request

**Comment by geekyJock8** [comment] 2019-08-17 17:26
This issue has been closed but I'm using the latest version(1.11) and I'm still getting the error: 
`Attempted to enable 'Augmented Images' which is not yet supported by Instant Preview.
Please build and run on device to use this feature.`
Any update on this will be appreciated!
