### ISSUE TITLE
Texture height and width equal 0

### ISSUE THREAD

**Issue by filipsladek** [google-ar/arcore-unity-sdk#113] opened 2018-02-25 06:12 UTC
`Frame.CameraImage.Texture` has height and width set to 0.
Isn't it trivial to make it right?

**Comment by iBicha** [comment] 2018-02-26 02:21
#76

**Comment by chaosemer** [comment] 2018-02-27 19:56
Closing this as a dupe of #76.

**Closed by chaosemer** 2018-02-27 19:56 UTC
