### ISSUE TITLE
Multi-camera error  " GL_INVALID_ENUM: enum argument out of range"

### ISSUE THREAD

**Issue by LuLuPaPa** [google-ar/arcore-unity-sdk#386] opened 2018-09-11 07:08 UTC
If the scene contains “First Person Camera” and another camera, an error is reported at startup.
Error message: “OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_ENUM: enum argument out of range"
Arcore version：1.4.0
Unity version: 2017.4.10
I checked the #3  method, but didn't understand it.
I don't know what to do with it，Any help is much appreciated.

**Comment by LuLuPaPa** [comment] 2018-09-12 01:53
I have checked #368 , same as my question. Thank you very much.
This problem doesn't affect the use of ARcore,I don't know if there are any pitfalls in the future.

**Comment by small-potatoes** [comment] 2018-09-21 19:13
Thanks for the report, closing as duplicate of #368 .

**Closed** 2018-09-25 06:56 UTC
Labels: duplicate
