### ISSUE TITLE
Image data base not showing and getting console error

### ISSUE THREAD

**Issue by LeoMatcham** [google-ar/arcore-unity-sdk#411] opened 2018-10-05 14:56 UTC
![arcore database](https://user-images.githubusercontent.com/36663848/46542703-f97b2380-c8b6-11e8-8383-83d553fd58c4.PNG)

Hey, I'm getting this error and the image database is not showing up for me to check quality and also stopping me from building.

Any Ideas?

Unity version 2018.2.11f1
ARCore version is v1.50

**Comment by nilsk123** [comment] 2018-10-08 20:16
Ran into this too

**Comment by pablisho** [comment] 2018-10-09 17:28
Hi, thanks for the report. I added it to our internal tracker. As a workaround, try avoiding spaces in project path. Let me know if that helped.

**Comment by fredsa** [comment] 2019-01-10 23:09
Duplicate of #297

**Closed by fredsa** 2019-01-10 23:09 UTC
Labels: bug
