### ISSUE TITLE
Pinch zoom is not working while object in horizontal planes in unity

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [google-ar/arcore-unity-sdk#170] opened 2018-04-17 08:16 UTC
Iam using unity to develop ARCore applications.i was using pinch zoom functionality to the 3d object.pinch zoom is not working while object in Horizontal plane  but it was worked when i place object other places without horizontal plane.How can i solve the issue?

My code for pinch zoom is:

` 
 if(Input.touchCount==2)
            {

                if(touch.phase==TouchPhase.Began)
                {
                    initialFingersDistance = Vector2.Distance(Input.touches[0].position, Input.touches[1].position);
                    if(showParts=="true")
                    {
                        initialScale = arObjectsParts.transform.localScale;
                    }
                    else
                    {
                        initialScale = arObjects.transform.localScale;
                    }
                    
                }
                else
                {
                    float currentFingerDistance = Vector2.Distance(Input.touches[0].position, Input.touches[1].position);
                    float ScaleFactor = currentFingerDistance / initialFingersDistance;
                    if(showParts=="true")
                    {
                        arObjectsParts.transform.localScale = initialScale * ScaleFactor;
                    }
                    else
                    {
                        arObjects.transform.localScale = initialScale * ScaleFactor;
                    }
                    
                }
            }
`

**Comment by pablisho** [comment] 2018-05-01 16:35
Hi, when you say the object is in an horizontal plane, you mean you created it with an Anchor as parent, right?
I don't see any difference there regarding the scale, what is your expected behaviour and what do you experience?
To better debug your problem I would remove the pinch zoom logic and just set the local scale to a fixed number to understand better what is happening when it's attached to an Anchor and when it's not.

**Comment by ArigarasuthanRepo** [comment] 2018-05-04 06:42
Sorry i made mistake in my code i corrected.Thanks for the response.

**Comment by pablisho** [comment] 2018-05-04 14:01
Cool! I'm closing this because you issue is resolved. Feel free to reopen or open a new one if you experience ARCore issues.

**Closed by pablisho** 2018-05-04 14:01 UTC
