### ISSUE TITLE
Add Augmented Image target at runtime

### ISSUE THREAD

**Issue by HolyManoly** [google-ar/arcore-unity-sdk#256] opened 2018-06-11 06:56 UTC
Hi guys, why is adding new Augmented Images at runtime not available inside of a build on Android devices ? The documentation clearly states that it can be done, while I'm not able to compile a build that has this feature.

**Comment by bopangzz** [comment] 2018-06-11 18:58
Adding new images at runtime is not exposed in Unity API right now. Can I ask is there any use case in particular that you need to add new image at runtime? Be aware, adding image at runtime is a time consuming behavior.

**Comment by mende-pion-one** [comment] 2018-06-12 12:51
@bopangzz Adding or changing the image in the app will make the app more dynamic not only for the user. As developer we dont have to build  a new app everytime, just for changing an image, if its desired from user.

**Comment by HolyManoly** [comment] 2018-06-12 13:05
Yes, the idea is to download images from the server at runtime and to generate targets from those images.

**Comment by BeachedCactus** [comment] 2018-06-18 13:54
It would be great to see this feature implemented or the ability to change the image database at runtime once downloaded from a server.

**Comment by iHoody** [comment] 2018-06-18 14:01
We are also eagerly awaiting this to be available

**Comment by adgluzdov** [comment] 2018-06-28 15:22
Is there a way to solve this problem with assets (fill asset with augment image database and load this component)?

**Comment by me-Stoffel** [comment] 2018-07-24 11:11
Would also be interested in finding a way to achieve this or have this feature implemented. Any known workaround?

**Comment by ryan-motive** [comment] 2018-07-24 18:43
We have a solution in house that we'll be rolling out with our updated templates next month along with authoring support for the markers.

www.motive.io

**Comment by bryanliujh** [comment] 2018-09-12 02:49
Would love to know when it will be rolling out....

**Comment by ryan-motive** [comment] 2018-09-12 03:03
We actually just rolled it out in our Explore AR 1.4 template--this supports both ARKit and ARCore dynamic image targets in Unity:

https://github.com/motive-io/Explore-AR

Unfortunately there's no editor support for them, you'll have to put it on a device to get it working.

**Comment by pablisho** [comment] 2018-09-27 20:46
Hi, [ARCore SDK for Unity 1.5.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.5.0) has been released and this issue should be fixed. Please feel free to comment if you still experience it.

**Closed by pablisho** 2018-09-27 20:46 UTC
Labels: feature request, fixed in upcoming release

**Comment by mende-pion-one** [comment] 2018-09-28 09:00
Hi, is there any example for ARKIT 1.5.0 how to set  up "AugmentedImages at Runtime" in Unity or is there some documentation available?Thanks in advance.

**Comment by mende-pion-one** [comment] 2018-09-28 09:01
> .

Hi, is there any example for ARKIT 1.5.0 how to set up "AugmentedImages at Runtime" in Unity or is there some documentation available?Thanks in advance.

**Comment by Noobay** [comment] 2018-10-04 07:33
since this feature had been added, and I have had a (really) minor issue with it, 
I'm just posting to let everyone know that the supported Texture formats are RGB24 and RGBA32 .
in my project, the loaded texture defaulted to ARGB32, and it took me some time to figure out that it was the issue.

**Comment by Gazuria** [comment] 2018-10-10 19:27
> since this feature had been added, and I have had a (really) minor issue with it,
> I'm just posting to let everyone know that the supported Texture formats are RGB24 and RGBA32 .
> in my project, the loaded texture defaulted to ARGB32, and it took me some time to figure out that it was the issue.
> 
> Source - ([_ConvertTextureToGrayscaleBytes](https://github.com/google-ar/arcore-unity-sdk/blob/082eda24e9abbf7854503c9c2496bab6e8413584/Assets/GoogleARCore/SDK/Scripts/Api/AugmentedImageDatabaseApi.cs) )

@Noobay I'm unable to add new images to a db, I'm getting this error, can you share an example?

EntryPointNotFoundException: ArPrestoAugmentedImageDatabase_create
GoogleARCoreInternal.AugmentedImageDatabaseApi.CreateArPrestoAugmentedImageDatabase (System.Byte[] rawData) (at Assets/GoogleARCore/SDK/Scripts/Api/AugmentedImageDatabaseApi.cs:59)
GoogleARCore.AugmentedImageDatabase.get_m_ArPrestoDatabaseHandle () (at Assets/GoogleARCore/SDK/Scripts/AugmentedImageDatabase.cs:104)
GoogleARCore.AugmentedImageDatabase.AddImage (System.String name, UnityEngine.Texture2D image, Single width) (at Assets/GoogleARCore/SDK/Scripts/AugmentedImageDatabase.cs:170)

**Comment by avanhale** [comment] 2019-01-10 18:36
Confirmed working, however, it seems assignment of another AugmentedImageDatabase to the session config also works during runtime which is handy. I would like to construct a database with one image by using AddImage and then assigning this to config, but I cannot seem to get this working on target device. Has anyone tried this before?

**Comment by Akash437** [comment] 2019-02-26 03:40
Is there a way to know that the image am currently scanning  is not in the  AugmentedImageDatabase that is currently assigned to session. something like a "database scan complete with no image found" callback ?

**Comment by DerrickBarra** [comment] 2019-04-04 18:15
Adding a texture to the image database at runtime doesn't seem to work. ARCore says the image has been added to the session.config.augmentedImageDatabase (the image database count goes up +1 and the AddImage method returns a valid index number).

However, when you actually try scanning for the image, the Update() function used in the AR Image example is unable to find it, with 0 AugmentedImage's being returned via Session.GetTrackables<AugmentedImage>().

However, if we make the database in the editor and add the image that way, everything works.

Anyone have any advice or willing to send a link to a confirmed working demo scene using dynamic image targets? I've tried a lot of different tests and scoured the internet but I need help. Our app heavily depends on this feature.

**Comment by vishnuharidas** [comment] 2019-08-17 09:05
Any progress in this? I am trying to update the database during runtime with images picked from the user's Gallery, but it doesn't work anyway. As everyone said, the database returns a positive number when adding images at runtime.

Comment if someone could achieve adding image targets during runtime.

**Comment by AMaceikaCortina** [comment] 2019-08-20 18:33
I am also trying to do this since I want to update the database during runtime so I can create a test app for our designers to check different markers and how well they work.  I don't get why people continue to call this closed when this is not working.

**Comment by geekyJock8** [comment] 2019-08-31 08:57
Any update on this?
I'm not even getting positive numbers on the latest version. It just keeps returning -1.
I've enabled read/write feature, set texture format to RGBA24, tried it with new AugmentedImageDatabase at runtime(using ScriptableObject), tried it with existing AugmentedImageDatabase, tried it in the editor, tried the build on android, tired it in instant preview but no luck.
Is there something that I'm missing?

**Comment by geekyJock8** [comment] 2019-09-04 11:44
So, I got this working!
If anyone is still struggling with this, here's the solution:

1.  Create a new database:
`AugmentedImageDatabase newDatabase`
 `= ScriptableObject.CreateInstance<AugmentedImageDatabase>();`
2. Make sure that all the images which you are using, have Read/Write enabled and format = RGB 23 bit.
3. Make sure that there's a delay between the start of your scene and the call of the function `newDatabase.AddImage(name, image)`. You can do this by passing a counter check-in Update function and delay the addition of images by around 40-50 frames.

Due to some reason, if you add the images in start function, most of the times, it returns -1 because I think that native session is still not initialised (`LifecycleManager.Instance.NativeSession`).

**Comment by manojghorela69** [comment] 2019-09-18 08:39
Can we add the database image from gallary or server, and render the assets provided with the image. I want to fetch the 3D model from url and render it on the added image.
Thanks

**Comment by joelchitunda** [comment] 2019-10-18 15:14
Is there a way to do this in android studio?
Sorry. I am very new to ARCore ,only  started working with android studio for a month and I am also a begginer. Any help is welcome :)
I tried unity but it seemed more difficult than android studio ( correct me if I am wrong but unity works with c# , which I don't know yet).

Do you guys know or have an example of adding an image from the user's phone gallery to the augmented images database at runtime? What I would like to do is to add a button in the beginning (before the ARCore session starts) of the app so the user can configure the databse.

**Comment by Mackands** [comment] 2020-09-22 07:59
> So, I got this working!
> If anyone is still struggling with this, here's the solution:
> 
> 1. Create a new database:
>    `AugmentedImageDatabase newDatabase`
>    `= ScriptableObject.CreateInstance<AugmentedImageDatabase>();`
> 2. Make sure that all the images which you are using, have Read/Write enabled and format = RGB 23 bit.
> 3. Make sure that there's a delay between the start of your scene and the call of the function `newDatabase.AddImage(name, image)`. You can do this by passing a counter check-in Update function and delay the addition of images by around 40-50 frames.
> 
> Due to some reason, if you add the images in start function, most of the times, it returns -1 because I think that native session is still not initialised (`LifecycleManager.Instance.NativeSession`).

how you do the create new database script, do you use the script AugmentedImageDatabase or do you reedit the AugmentedImageDatabaseContextMenu script to adjust your need, i tried adjust the script AugmentedImageDatabaseContextMenu, can insert new image target, but somehow the texture missing, but if the texture in there, the quality become calculating.......
