### ISSUE TITLE
eGPU and instant preview

### ISSUE THREAD

**Issue by camnewnham** [google-ar/arcore-unity-sdk#416] opened 2018-10-11 00:15 UTC
I have instant preview working as described on my XPS 13 9370 and Unity 2017.4.12f1 (ARCore 1.5) with a Samsung Galaxy S7. The camera feed is fed into the unity editor.

I'm attempting to get preview mirroring working with an eGPU (Aorus Box 1070). The NVIDIA utility reports that Unity is running on the GPU, but instant preview still does not mirror to the mobile device.

Has anyone managed to get this working, is it a known limitation and/or is it intended to be addressed? Happy to run any debugging scenarios that may help.

**Comment by pablisho** [comment] 2018-10-26 19:52
Hi, Instant Preview currently has some limitations regarding the GPU, see https://developers.google.com/ar/develop/unity/instant-preview, so I think this is a known current limitation. @small-potatoes is there any plan to address this in the near term?

**Comment by fredsa** [comment] 2019-01-11 01:00
Duplicate of #484

**Closed** 2019-01-11 01:00 UTC
Labels: duplicate, feature request
