### ISSUE TITLE
InstantPreview hangs Unity changing the game window size

### ISSUE THREAD

**Issue by ivan2007** [google-ar/arcore-unity-sdk#479] opened 2019-01-07 10:15 UTC
### VERSIONS USED
- Unity: 2018.3.0f2
- ARCore SDK for Unity: 1.6.0
- Device manufacturer, model, and O/S: Xiaomi Mi8
- ARCore: 1.6.181112096
- Xiaomi/dipper/dipper:9/PKQ1.180729.001/V10.1.2.0.PEAMIFI:user/release-keys

### STEPS TO REPRODUCE THE ISSUE
 1. Create a new Unity 3d project
 2. Import ARCore package (drag and drop HelloAR scene)
 3. Play
 4. Change the game window size

**Comment by fredsa** [comment] 2019-01-09 00:45
Duplicate of #287

**Closed by fredsa** 2019-01-09 00:45 UTC
