### ISSUE TITLE
Editor crash with Instant Preview and Focus Mode: Auto

### ISSUE THREAD

**Issue by camnewnham** [google-ar/arcore-unity-sdk#422] opened 2018-10-16 05:16 UTC
Instant preview appears to crash the editor with focus mode set to auto.
This happens regardless of whether instant preview is turned on in the ARCore settings.

Tested on editor versions 2017.4.12f1 LTS and 2017.4.13f1 LTS, Windows 10 10.0.16299 on Dell XPS 9370 (integrated graphics).

Steps to reproduce:

1. Start new project
2. Import ARCore
3. Configure and enable ARCore in XR settings, set build target to android
4. Note that instant preview works
5. Change session config to set focus mode to auto
6. Note that instant preview crashes unity editor, even when disabled in project settings

Appears to be access violation, described below in log.

```
Unity Editor [version: Unity 2017.4.12f1_b582b87345b1]

arcore_instant_preview_unity_plugin.dll caused an Access Violation (0xc0000005)
  in module arcore_instant_preview_unity_plugin.dll at 0033:7c49e28f.

Error occurred at 2018-10-16_160946.
C:\Program Files\Unity\Hub\Editor\2017.4.12f1\Editor\Unity.exe, run by (me).
43% memory in use.
16193 MB physical memory [9136 MB free].
19009 MB paging file [10377 MB free].
134217728 MB user address space [134215317 MB free].
Read from location 00000000 caused an access violation.
... (trimmed)
== [end of error.log] ==


```

**Comment by pablisho** [comment] 2018-10-26 20:05
Hi, thanks for the report and the details. I added to our internal tracker.

**Comment by Noobay** [comment] 2018-11-10 22:00
happens to me as well

**Comment by Noobay** [comment] 2018-11-10 22:08
happens to me too, requires cloud anchors AND auto focus to be active

`Unity Editor by Unity Technologies [version: Unity 2018.1.2f1_a46d718d282d]

arcore_instant_preview_unity_plugin.dll caused an Access Violation (0xc0000005)
  in module arcore_instant_preview_unity_plugin.dll at 0033:a10de28f.

Error occurred at 2018-11-11_000344.
C:\Program Files\Unity\Hub\Editor\2018.1.2f1\Editor\Unity.exe, run by MIXED.PLACE-ADAR.

28% physical memory in use.
32724 MB physical memory [23422 MB free].
1774 MB process peak paging file [1629 MB used].
1186 MB process peak working set [1042 MB used].
System Commit Total/Limit/Peak: 13332MB/37588MB/19660MB
System Physical Total/Available: 32724MB/23422MB
System Process Count: 259
System Thread Count: 3936
System Handle Count: 129513
Disk space data for 'C:\Users\SomeUser\AppData\Local\Temp\Unity\Editor\Crashes\Crash_2018-11-10_220339959\': 18167578624 bytes free of 254930841600 total.

Read from location 0000000000000000 caused an access violation.

Context:
RDI:    0x00007ffda1109aa0  RSI: 0x0000000000000001  RAX:   0x000000003b084490
RBX:    0x000000003b084490  RCX: 0x00007ffda10de28f  RDX:   0x0000000000000000
RIP:    0x00007ffda10de28f  RBP: 0x0000000000000000  SegCs: 0x0000000000000033
EFlags: 0x0000000000010202  RSP: 0x00000000005fd168  SegSs: 0x000000000000002b
R8:     0x0000000000000001  R9:  0x00007ffda10b0000  R10:   0x0000000000000000
R11:    0x000000003b084490  R12: 0x0000000000000000  R13:   0x0000000062b424d0
R14:    0x00000000005fd820  R15: 0x000000001cfb31c0


Bytes at CS:EIP:
0f b6 0a 88 08 c3 f3 0f 6f 02 f3 0f 7f 00 c3 66 

Mono DLL loaded successfully at 'C:\Program Files\Unity\Hub\Editor\2018.1.2f1\Editor\Data\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll'.


Stack Trace of Crashed Thread 14004:
0x00007FFDA10DE28F (arcore_instant_preview_unity_pl) Update
0x00007FFDA10BBBC8 (arcore_instant_preview_unity_pl) Update
0x00007FFDA10BB887 (arcore_instant_preview_unity_pl) Update
0x000000003FEFD69C (Mono JIT Code) <unknown class>.<unknown method>()
0x000000003FEFCA4B (Mono JIT Code) <unknown class>.<unknown method>()
0x000000003FEFC5E3 (Mono JIT Code) <unknown class>.<unknown method>()
0x000000003FEFC390 (Mono JIT Code) <unknown class>.<unknown method>()
0x000000004567EC58 (Mono JIT Code) <unknown class>.<unknown method>()
0x00007FFD7732A1AB (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FFD772B1A42 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FFD772BAA2F (mono-2.0-bdwgc) mono_runtime_invoke
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 0000000140BDD21A)
`

**Comment by rodcibils** [comment] 2018-11-12 15:21
I'm experiencing the same issue with Instant Preview, with Camera Focus Mode on "Auto" and Cloud Anchors disabled. The crash seems to be related with the focus and not the cloud anchors.

**Comment by fredsa** [comment] 2019-01-11 01:04
Duplicate of #484

**Closed by fredsa** 2019-01-11 01:04 UTC
Labels: Instant Preview, bug
