### ISSUE TITLE
3D mapping (indoor)

### ISSUE THREAD

**Issue by juanmajr93** [google-ar/arcore-unity-sdk#162] opened 2018-04-09 17:26 UTC
Hi all,

I am a developer who are working with arcore in Unity. I have an idea which share you to know your opinions. I have made a scan of indoor space into our college building. It contains floor area, walls, some particular objects, etc. Well, computer vision app provides in real-time another point cloud. If I try to align this to my first point cloud, I can know my position and orientation in the map. do you agree?

Best regards,

Jjurado

**Comment by pablisho** [comment] 2018-04-10 15:06
Hi, what I would suggest is to think the problem in the opposite way. If you have a map or pointcloud of your current room, I wouldn't try to make ARCore localize in that space, but to actually find a way to place your pointcloud / map in your current world coordinates when you start your ARCore app.
If you find that transformation, then indeed it is the inverse of the transform from ARCore world coordinates to your map, so with knowing the device position respect to world coordinates (ARCore provides that) and the transform from ARCore world to your map, you could know the device position respect to your map.

**Comment by juanmajr93** [comment] 2018-04-10 16:43
It is not a solution. I mean, the gps precision of mobile phone has an error around 5 or 4 meters. For indoor positioning and orientation it is not supported. The point cloud of my room is geolocated but  when I will have to depict some AR object I have to determine the position and orientation of myself. This is the reason why I have propose the alignment between my original point cloud and the point cloud managed from computer vision app (ArCore).

**Comment by pablisho** [comment] 2018-06-04 20:40
Hi, I believe this is a duplicate of #226. Feel free to reopen if you still have questions about this, and or feature requests.

**Closed by pablisho** 2018-06-04 20:40 UTC
