### ISSUE TITLE
ARCore manager can't enable session on runtime .NET 4.X - black screen.

### ISSUE THREAD

**Issue by Ursanon** [google-ar/arcore-unity-sdk#265] opened 2018-06-19 10:28 UTC
Hey,
On Unity 2018.1 ARCore manager can't enable session, session status is "None" what produces black screen. Occurs only on scripting runtime .NET 4.X (.Net 3.5 seems to be working).
It may be returning of #172 bug.

Reproduction:
Build with runtime .NET 4.X and run app

```
public void EnableSession()
{
        // ...
    SetConfiguration(SessionComponent.SessionConfig);
        // on .NET 4.X never got logs below
    Debug.Log($"{this.GetType()} configuration done!"); 

    ExternApi.ArPresto_setEnabled(true);
    Debug.Log($"{this.GetType()} enabled!");
}
```

**Comment by vscalet** [comment] 2018-06-20 10:48
We have the same bug on unity 2018.1.5f1

**Comment by bopangzz** [comment] 2018-06-20 18:02
Thanks for the bug report. I can reproduce the issue and I will added it to our internal issue tracker.

**Comment by Ursanon** [comment] 2018-07-03 07:52
Sorry for the late reply, I missed notification.

Here are some logs.
[logcat.txt](https://github.com/google-ar/arcore-unity-sdk/files/2158152/logcat.txt)
[logcat2.txt](https://github.com/google-ar/arcore-unity-sdk/files/2158153/logcat2.txt)

**Comment by pablisho** [comment] 2018-09-03 16:38
Hi, I cannot reproduce this issue with ARCore 1.4  and looking at the error in the logs I believe this issue was fixed in our recent releases. Feel free to reopen if you still experience the issue.

**Closed by pablisho** 2018-09-03 16:38 UTC
Labels: bug
