### ISSUE TITLE
camera preview data can't update

### ISSUE THREAD

**Issue by feixiaku** [google-ar/arcore-unity-sdk#24] opened 2017-09-28 09:09 UTC
Hi, I met a problem that sometimes rare-camera data can't update, but my 3D model still update. But I haven't met this problem when my project don't use realtime shadow. unity version: 2017.2.0f1, Phone: Google pixel. Is this problem caused by Unity or ARCore SDK?

**Comment by nathanmartz** [comment] 2017-10-09 04:31
Can you share a simple project that reproduces the error?

**Comment by feixiaku** [comment] 2017-10-12 09:32
sorry, make a simple project is not convenient, but I can support a video and error log first, pls check it. thx.
[arcore-video.zip](https://github.com/google-ar/arcore-unity-sdk/files/1378793/arcore-video.zip)

catch the error log through Android Studio:
10-12 04:16:54.377 4947-5060/? E/tango: filter_update_base.cc:87 Temporary visual feature update failed when computing its residual and Jacobian.

**Comment by feixiaku** [comment] 2017-10-13 10:03
sorry, make a simple project is not convenient, but I can support a video [https://youtu.be/A8CVCoBbIm8](url) and error log first, pls check it. thx.

catch the error log through Android Studio:
10-12 04:16:54.377 4947-5060/? E/tango: filter_update_base.cc:87 Temporary visual feature update failed when computing its residual and Jacobian.

**Comment by chaosemer** [comment] 2017-10-13 23:15
If you can't share the project, could you share the full logcat when running this or (even better) an APK that shows this issue?

**Comment by feixiaku** [comment] 2017-10-16 09:29
Thanks for your reply. here is the [apk's link](https://drive.google.com/open?id=0B5Ii_xgfqSPGd0hka3N3MzF1Y00), the file exceeds the upper limit allowed by the attachment, so I put it on google drive. please check it.

**Comment by chaosemer** [comment] 2017-10-16 16:57
I was unable to reproduce the issue, however I noticed that your app has a lot of exceptions it logs during normal interaction:

ArgumentOutOfRangeException: Argument is out of range.
10-16 09:45:08.113 14297 14313 E Unity   : Parameter name: index
10-16 09:45:08.113 14297 14313 E Unity   :   at System.Collections.Generic.List`1[System.String].get_Item (Int32 index) [0x00000] in <filename unknown>:0
10-16 09:45:08.113 14297 14313 E Unity   :   at MeshController.AutoPlay () [0x00000] in <filename unknown>:0

If an exception is thrown at a bad time during update, it could cause the update of the AR background to break. I suggest removing all these exceptional cases and seeing if you can still repro the issue.

**Comment by nathanmartz** [comment] 2017-10-16 17:14
I'm going to close this as it's most likely unrelated to ARCore. Please reopen if the issue persists once exceptions are fixed.

**Closed by nathanmartz** 2017-10-16 17:14 UTC

**Comment by feixiaku** [comment] 2017-10-17 05:45
@chaosemer your log shows didn't find the video.  I think maybe you didn't put "urls_arcore.txt" or "model-2.nut" files into /sdcard/ directory. you can use these commands( "adb push urls_arcore.txt  /sdcard/", "adb push model-2.nut /sdcard/" ), then open the app. and I catch the full logcat: 
[arcore_logcat.txt](https://github.com/google-ar/arcore-unity-sdk/files/1389896/arcore_logcat.txt). 
please ensure this things, thanks.

**Comment by chaosemer** [comment] 2017-10-18 02:52
I pushed as well but am still getting errors:

Mesh 'Cube Instance': abnormal mesh bounds - most likely it has some invalid vertices (+/-inifinity or NANs) due to errors exporting.
Mesh bounds min=(-inf, -inf, nan), max=(nan, nan, inf). Please make sure the mesh is exported without any errors.

Tapping again appears to do something, but I never see a person appear. Can you create another build that doesn't dynamically load the .nut file?

**Comment by feixiaku** [comment] 2017-10-18 05:22
sorry, Don't Dynamically load the .nut file is not very easy.
I know this error log, but I think it doesn't related about this problem. I update the [apk](https://drive.google.com/open?id=0B5Ii_xgfqSPGQ0dQb1RnRDJhLWc) . 

After "Searching for surfaces" disappear, you can tap the screen, model will appear.
![screenshot_20171018-000530](https://user-images.githubusercontent.com/9450152/31701817-7e0f9332-b405-11e7-893d-c442ed06c096.png)

you can tap screen, 3D model will appear. you can try it again. And, this problem is not always appear,  so, you can try more times. 
we found sometimes the camera's preview data can't update when playing our 3D video with Unity's realtime shadow, but it always can update when playing 3D video without realtime shadow.  you can click **LightControl** Button to determine if Directional Light stay in the scene or not.

**Comment by feixiaku** [comment] 2017-10-19 06:40
@chaosemer @nathanmartz  have you reproduce the issue? the new apk have any problem?

**Comment by chaosemer** [comment] 2017-10-19 21:00
I'm very sorry, but trying to run your new .apk file I am still unable to reproduce the person appearing. I now no longer see planes either.

I am running this on a Pixel XL on Android O, could you please verify that this is the same environment as you?

**Comment by feixiaku** [comment] 2017-10-20 04:09
I feel very sorry. I have checked it again. The .nut file i have given you has some problem. I give you another[ .nut file](https://drive.google.com/open?id=0B5Ii_xgfqSPGclJBamN2TW5kcmM). you also need put the .nut file into /sdcard directory(adb push model-2.nut  /sdcard/). 
if you have a result. pls let me know, thanks

**Comment by chaosemer** [comment] 2017-10-21 00:17
Thank you! I am able to reproduce this issue 100% now.

I noticed that when I place the person, I always get the camera preview not updating. However, if I press the button marked "LightControl" twice, the camera preview will start updating again.

I'm suspecting that you are potentially using multiple Camera objects in your scene, and toggling which Camera you are using based on app state. For the ARCore developer preview you must use only one Camera for your entire session. If you want to toggle behavior, instead you should put additional scripts on the camera in the prefab.

**Comment by feixiaku** [comment] 2017-10-21 03:48
Great! Thank you very much. In my scene, there is only one camera. 
<img width="781" alt="screen shot 2017-10-21 at 11 16 40 am" src="https://user-images.githubusercontent.com/9450152/31847599-b64fc322-b651-11e7-8cce-82fa35f8307c.png">

And, the button "LightControl" only do one thing switching on/off **Directory Light**. if **Directory Light** enabled in the scene, realtime shadow will be rendered which you can in the scene. or, realtime shadow will disappear.  
<img width="964" alt="screen shot 2017-10-21 at 11 22 08 am" src="https://user-images.githubusercontent.com/9450152/31847658-362e5284-b652-11e7-8bfb-695c83faa6c1.png">

Besides, there is another situation. when camera's preview data blocked, if you turn your phone in other direction that you can not see the model, camera's preview data update again, but if you turn back the phone to 3D model's direction, camera's preview data blocked again. I think maybe it is rendering process takes too much time  that caused the failure of camera preview data update.

Due to the final image show on the phone is blend by Android camera's preview data and UnityEngine's rendered texture. Does something make the camera's preview data blocked?

**Comment by chaosemer** [comment] 2017-10-23 05:31
I tried to create a minimal repro case myself playing with directional lights and could not.

What I really need now is for you to create a minimal repro project and share it with me. You can find my email address on my [profile](https://github.com/chaosemer) so you can restrict sharing to just me.
