### ISSUE TITLE
Declare Individual Video on Each Image Database

### ISSUE THREAD

**Issue by prassprass** [google-ar/arcore-unity-sdk#421] opened 2018-10-16 01:39 UTC
Hi, I've learned that it's possible to use ARCore to play video based on ImageDatabase as shown link bellow:
https://www.youtube.com/watch?v=sX1aOBlwGWc&t=436s

Is it possible to play different videos on each image that stored on ImageDatabase?

Thanks for answering.

**Comment by pablisho** [comment] 2018-10-26 20:07
Hi, you can use [AugmentedImage.Name](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/AugmentedImage.cs#L63) to do your logic depending on which image was detected. Let me know if this helps.

**Comment by prassprass** [comment] 2018-10-27 00:57
@pablisho could you tell me specifically where should i put AugmentedImage.Name? i just couldn't figure it out where to put that.

thanks for answering

**Comment by chaosemer** [comment] 2018-11-21 17:32
You set each AugmentedImage's name in the editor in your database. See https://www.youtube.com/watch?v=sX1aOBlwGWc&t=6m10s in the video.

Then when you are placing the video, you'll want to look at what the value of AugmentedImage.Name is for the recognized image to choose what video to play.

I hope this helps. I'm closing this Issue as this is not a bug.

**Closed by chaosemer** 2018-11-21 17:32 UTC
