### ISSUE TITLE
Camera aspect ratio issue

### ISSUE THREAD

**Issue by eisenbruch** [google-ar/arcore-unity-sdk#40] opened 2017-10-20 20:01 UTC
We are aware of the screen stretch issue on s8 and pixel 2 XL, but I am having a different issue. My camera view is stretched out horizontally very far. I am not sure if this is due to an issue with ARCore and the newest Unity beta, or if it is something I did wrong in my app. 

This object should be a near perfect circle:
![screenshot_20171019-184101](https://user-images.githubusercontent.com/6180294/31839623-e86ae2e4-b5af-11e7-9bc0-fb6417158e82.png)

Any thoughts, or is this happening to you?

**Comment by eisenbruch** [comment] 2017-10-24 00:54
This is happening across all my projects and even happens if I start a new project and import the ARCore package and just run the example. I have gone through all my settings many times and I am starting to think it's a ARCore issue, although I have not seen it reported elsewhere. Is there anyway I can help investigate this further?

**Comment by chaosemer** [comment] 2017-10-26 06:59
Providing a minimal repro project is super helpful. Could you please share the source for such a project? The best would be if you can figure out how to get the sample to do this.

**Comment by eisenbruch** [comment] 2017-10-26 14:06
Absolutely, here is my project created with Unity 2017.3.0b5, all I did was setup a new project, add in the ARCore unity package and follow other steps on the getting started page, and built the app.

https://github.com/eisenbruch/ARCoreExample

Looking forward to hearing if you have the same issue as I do...

**Comment by iHzm** [comment] 2017-10-26 14:28
Did you go into the game tab and try to set the aspect ratio to 16:9 and set the resolution to 1920x1080?

**Comment by eisenbruch** [comment] 2017-10-26 14:49
Hi @iHzm :)
I have tried that in 2 ways:
![screen shot 2017-10-26 at 10 48 12 am](https://user-images.githubusercontent.com/6180294/32059819-376072a8-ba3b-11e7-92de-a158bf33dce1.png)
![screen shot 2017-10-26 at 10 46 19 am](https://user-images.githubusercontent.com/6180294/32059820-376dbdfa-ba3b-11e7-8a53-a4b67df53fc9.png)

The stretching issue persists if I build my game with either of those selected in the Game tab.

**Comment by fredsa** [comment] 2017-11-01 18:11
Duplicate of #16

**Comment by eisenbruch** [comment] 2017-11-01 18:19
@fredsa can you please explain how this is the same as the s8 vertical stretching issue? I am curious as they seem to be different to me. Are you able to supply a link to the unity bug in a unity bug tracker?

**Comment by fredsa** [comment] 2017-11-01 21:14
@eisenbruch If you're seeing the incorrect stretch / camera aspect ratio on the S8, then I think we should track it in issue #16.

If you're experiencing the issue on other devices, please let us know.

**Comment by eisenbruch** [comment] 2017-11-01 22:54
@fredsa as stated in the original post I believe I am seeing some vertical stretch due to extra tall screen on my Pixel 2 XL, as is similar on the S8. So that is a different device that has that vertical stretch particular issue.

However, the reason why I started this post is actually a different issue. As you can see in the image in the top post, I am seeing a severe horizontal stretch in the camera view on my Pixel XL and Pixel 2 XL. 

Since this is horizontal stretch and on a different device, I do not believe that this issue is a duplicate of #16.

**Comment by fredsa** [comment] 2017-11-02 01:57
Thanks for clarifying. Attaching a screenshot of a stretched (should be round) soda can top, taken on a Pixel XL, with an ARCore app, built using Unity 2017.3.0b5.

![marlin_opr1 170623 032_2017-11-01-18-53-12](https://user-images.githubusercontent.com/1235362/32306009-26547a04-bf36-11e7-86ca-f8037c5e6fd1.png)

App orientation happens to be landscape in this app, but that's not affecting stretch.

**Comment by eisenbruch** [comment] 2017-11-10 18:37
Is Unity aware of this issue? Any idea on a fix release, or on the next release of ARCore?

**Comment by nathanmartz** [comment] 2017-11-14 00:03
Yes, they are. We're working with them to get a fix as soon as possible.

**Comment by eisenbruch** [comment] 2017-11-14 21:39
@nathanmartz / @fredsa as can be seen in @fredsa's photo posted on 11/1, our ARCore/Unity apps have an issue with camera focus. Is this ARCore specific, or a general Unity bug? Should I start a new issue for camera focus or is this something we'll see fixed in the next release?

**Comment by chaosemer** [comment] 2017-11-14 23:58
Camera focus distance is set at a fixed range that is ideal for tracking. There are not plans to change that for v1.0.

**Comment by eisenbruch** [comment] 2017-11-15 00:36
@chaosemer I see the logic behind that now. Thanks!

**Comment by holowraith** [comment] 2017-11-22 16:16
This is worse on Samsung S8 as of Unity 2017.3.0b10.  Now there are black bars on the sides in portrait or at the top and bottom in landscape that do not clear the frame buffer and artifact.  In addition the screen is squashed or stretched worse that it was before.  Previous release of 2017.3.0b3 worked a lot better.  Can you at least release the code for the TangoARRender.shader that is hidden away so we can fix this ourselves?  No adjustment of resolution or aspect ratio seems to fix and custom aspect ratio is no longer changeable in Unity either.

**Comment by eisenbruch** [comment] 2017-12-03 13:29
This is very unfortunately still an issue on 2017.3.0f1. It's impossible to make even decent quality AR experiences when the actual world doesn't even look good/accurate before adding digital elements.

**Comment by chaosemer** [comment] 2017-12-15 16:48
This should now be resolved in Developer Preview 2. Please reopen if you still are having issues.

**Closed by chaosemer** 2017-12-15 16:48 UTC
Labels: Unity bug
