### ISSUE TITLE
Does ARcore1.7 or earlier support unity LightWeight RP?

### ISSUE THREAD

**Issue by kushal98** [google-ar/arcore-unity-sdk#511] opened 2019-02-23 13:07 UTC
has anyone tried using arcore in unity light weight RP?

**Comment by emrecelik95** [comment] 2019-02-24 19:44
I've tried, but background stays black. I guess we have to get LWRP supported background material. If anyone made it, we want to know. Actually AR Foundation supports [LWRP](https://github.com/Unity-Technologies/arfoundation-samples/tree/lwrp_support), but I don't know how to do using only AR Core SDK.

**Comment by fredsa** [comment] 2019-03-01 19:27
Duplicate of #131

**Closed by fredsa** 2019-03-01 19:27 UTC
