### ISSUE TITLE
Arcore Help required on Pinch and Zoom

### ISSUE THREAD

**Issue by inio** [google-ar/arcore-unity-sdk#65] opened 2017-12-21 17:59 UTC
_From @rramjee on December 21, 2017 7:29_

I'm using Unity to to instantiate an industrial object on tap of the screen similar to Hello AR example. I want to be able to extend this by providing an option to pinch and zoom the object.  I'm not sure if I'm explaining myself well. if you look at the video on youtube "https://www.youtube.com/watch?v=dwWPSnog3Xo" and specifically between 2:14 to 2:20s of the video, they are able to pinch and zoom .  Basically, I'm looking for some guidance on how to pinch and zoom. 

_Copied from original issue: google-ar/arcore-android-sdk#96_

**Comment by chaosemer** [comment] 2017-12-22 17:21
You'll want to record the touch positions when the second touch starts and then adjust the scale as the touch moves.

You can see similar code in the Tango camera controller:
https://github.com/googlesamples/tango-examples-unity/blob/master/UnityExamples/Assets/TangoPrefabs/Scripts/TangoGestureCamera.cs#L201-L220

**Comment by chaosemer** [comment] 2017-12-22 17:21
Closing this since this is not a bug.

**Closed by chaosemer** 2017-12-22 17:21 UTC
