### ISSUE TITLE
Plane finding and light estimation can not be disabled in instant preview mode

### ISSUE THREAD

**Issue by few2net** [google-ar/arcore-unity-sdk#440] opened 2018-11-01 01:45 UTC
I used instant preview to test my project (with ARcore 1.4 and pixel phone2 ).
What I was doing is to give my application will detect horizontal plane only.
To do that, I changed a setting in session config.
I tried to build and run on my phone and It was work, but in instant preview mode It was not.
Btw, I found that not only plane finding mode but also light estimation
can't be changed in instant preview mode.

![capture](https://user-images.githubusercontent.com/40989302/47827790-ec792380-ddd3-11e8-84a5-f0126824331e.PNG)

**Comment by alikanat001** [comment] 2018-11-05 16:37
This is not an issue SDK already warns you about it when you attempt to disable surface detection in instant preview

**Comment by chaosemer** [comment] 2018-11-21 17:43
You are right, this is a feature request! 😄

**Comment by fredsa** [comment] 2019-01-10 22:09
Duplicate of #484

**Closed** 2019-01-10 22:58 UTC
Labels: Instant Preview, duplicate, feature request
