### ISSUE TITLE
the app should start or re-trigger the calibration"

### ISSUE THREAD

**Issue by afedorychak** [google-ar/arcore-unity-sdk#136] opened 2018-03-12 19:04 UTC
When the app cannot find enough space or the app is taking an excessive amount of time to identify a suitable plane for the app objects to anchor to, the app should start or re-trigger the calibration"

**Comment by chaosemer** [comment] 2018-03-12 21:30
Closing as duplicate of #137.

**Closed by chaosemer** 2018-03-12 21:30 UTC
Labels: duplicate
