### ISSUE TITLE
Augmented Image Visibility

### ISSUE THREAD

**Issue by joshliebe** [google-ar/arcore-unity-sdk#290] opened 2018-07-02 20:25 UTC
Hi team,

Is there a way to know when the tracking image is no longer visible to the device's camera?

For instance, taking the example scene, it successfully detects the image and shows the picture frame. If I hide the image, then the frame persists for some time but the image is no longer visible.

Is there a way to know that the image is no longer visible so that I could hide the frame?

![screenshot_20180702-220624](https://user-images.githubusercontent.com/3471025/42184535-2bb82f2a-7e46-11e8-9281-2078e57e4154.png)![screenshot_20180702-220635](https://user-images.githubusercontent.com/3471025/42184537-2d3b305e-7e46-11e8-8504-64df8acc80b3.png)

**Comment by pablisho** [comment] 2018-07-19 00:14
Hi, moving the target quickly is not currently supported by ARCore. You can check the Augmented Image [TrackingState](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Trackable.cs#L64), but this is what the Augmented Image example is doing and the delay that you see is expected.
I'm closing this as it's the current expected behaviour of ARCore.

**Closed by pablisho** 2018-07-19 00:14 UTC

**Comment by zyonneokid** [comment] 2018-11-28 04:48
The issue is still there....the prefab does not disappear even after long time

**Comment by alikanat001** [comment] 2018-12-07 10:40
You can take a look at [this](https://stackoverflow.com/questions/53642352/arcore-extended-imagetracking-anchoring-api-in-unity/53656523#53656523)
