### ISSUE TITLE
How to dynamically compare pictures？

### ISSUE THREAD

**Issue by lichenyigit** [google-ar/arcore-unity-sdk#350] opened 2018-08-13 09:25 UTC
I want to compare the image on the server with the image captured by arco and get the comparison result. What should I do?

**Comment by pablisho** [comment] 2018-08-13 15:15
Hi, could you explain a little more what you're trying to do? Are you using AugmentedImages? Why do you want to compare it with images in your server? With AugmentedImages, each image can have a name, you could use that to know which image was detected. Does that help?

**Comment by lichenyigit** [comment] 2018-08-14 01:29
Hi, thanks for the report. I am using AugmentedImages.Although AugmentedImages can be used to obtain information about the detected image. But I want the images in AugmentedImageDatabase to be updated in real time or at regular intervals.And the update picture comes from a remote server.

**Comment by pablisho** [comment] 2018-08-14 14:17
Hi, thanks for the explanation. Adding augmented images at runtime is not currently supported by ARCore SDK for Unity. I believe this is a duplicate of #256

**Closed by pablisho** 2018-08-14 14:17 UTC
