### ISSUE TITLE
Question: query ARCore support on any Android device

### ISSUE THREAD

**Issue by kenny-uken** [google-ar/arcore-unity-sdk#83] opened 2018-01-23 19:28 UTC
Sorry to keep opening issues! This is just a question, though.

What's the best way to ask the SDK if the current device + OS version is supported? I see there's ways to figure out if the device is unsupported when attempting to create an AR session, but we want to implement some UI flows that prevent the user from entering AR if their device isn't supported in the first place. This is made trickier by the fact that creating that doomed-to-fail session requires min SDK version 24, but we want to know on any device.

We are already planning to submit multiple APKs with different minimum SDK versions, so we might hardcode some kind of solution. We are already looking into maintaining a device whitelist. However, this really seems like something ARCore would ideally provide for us. Any suggestions?

**Comment by chaosemer** [comment] 2018-01-23 20:03
There is no way to currently do this. We are adding API surface for this in an upcoming release. Stay tuned!

**Comment by alons1** [comment] 2018-02-05 19:53
Or you can use Vuforia. They say they use ARcore whenever possible, and when it's not, they do their own (probably not as good) plane detection solution.

**Comment by kbobnis** [comment] 2018-02-28 19:37
Any news on the whitelist since the ARCore was released?

**Comment by alons1** [comment] 2018-02-28 19:50
I dont think you need it.
On your manifest there will be an ARcore required statement.
I believe that would cause it to not showup in google play for un supported devices.
And even if you omit this statement, there's an api for checking if ARcore service is installed

**Comment by kbobnis** [comment] 2018-02-28 19:52
That's all true, but the AR thing is just an option in our app. 

We want the app to be available for all phones and the AR option to show up only on whitelisted devices.

**Comment by alons1** [comment] 2018-02-28 19:56
So use Session.CheckApkAvailability()
And see if it returns ApkAvailabilityStatus.UnsupportedDeviceNotCapable

**Comment by chaosemer** [comment] 2018-03-01 01:23
Yup, what @alons1 said is exactly correct with 1.0.

I'm closing this issue as it is now resolved.

**Comment by ryan-motive** [comment] 2018-03-13 21:39
Are there any examples of this actually working? I'm making the call, but my "ThenAction" never gets invoked. I've tried this with a coroutine as well to no avail.

**Comment by ryan-motive** [comment] 2018-03-13 22:03
I've added comments throughout LifecycleManager. OnCheckApkAvailabilityResultTrampoline is never called.

**Comment by chaosemer** [comment] 2018-03-14 00:47
Ryan, could you provide a sample project that reproduces this issue? That'll help us track this down.

**Comment by paulodgn** [comment] 2018-04-03 14:05
Anyone managed to solve this problem? Im having the same issue, CheckAPKAvaiability works on a S7 but doesnt work on a android 6 device.

**Comment by kbobnis** [comment] 2018-04-03 16:06
Hi @paulodgn, 

It doesn't even need to be checked on android 6 device because this version is not supported by AR.

In Unity2017.3.1p2 you can build app with minimum SDK lower than 24 and have AR enabled.
Then we're checking if the device's android SDK is >= 24 before checking the apk availability.

**Comment by pablisho** [comment] 2018-05-09 00:08
Hi, this issue has been fixed in [ARCore Unity SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0). Feel free to reopen if you still experience the issue.

**Closed by pablisho** 2018-05-09 00:08 UTC
Labels: bug, fixed in upcoming release

**Comment by areavisuale** [comment] 2018-05-11 14:40
Are you sure the issue has been fixed? I'm using Unity 2018.1.0f2 and ArCore 1.2.0 and CheckAPKAvaiability works on a S7 but doesn't work on Huawei P9 lite (Android 7), Galaxy J5 (Android 5.1), Galaxy S3 (Android 4.3).
This is the code I'm using:

`using System.Collections;
using UnityEngine;
using GoogleARCore;
using UnityEngine.UI;

public class ARoptional : MonoBehaviour {

    // Use this for initialization
    void Start () {
        string name = SystemInfo.operatingSystem.ToString();
        int foundS1 = name.IndexOf("-");
        name = name.Substring(foundS1 + 1, 2);
        int api = int.Parse(name);
        Debug.Log("Device with API: " + api);
        if (api < 24)
        {
            Debug.Log("Unsupported device");
        } else
        {
            StartCoroutine(CheckCompatibility());
        }
    }

    private void _ShowAndroidToastMessage(string message)
    {
        AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
        AndroidJavaObject unityActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");

        if (unityActivity != null)
        {
            AndroidJavaClass toastClass = new AndroidJavaClass("android.widget.Toast");
            unityActivity.Call("runOnUiThread", new AndroidJavaRunnable(() =>
            {
                AndroidJavaObject toastObject = toastClass.CallStatic<AndroidJavaObject>("makeText", unityActivity,
                    message, 0);
                toastObject.Call("show");
            }));
        }
    }

    private IEnumerator CheckCompatibility()
    {
        AsyncTask<ApkAvailabilityStatus> checkTask = Session.CheckApkAvailability();
        CustomYieldInstruction customYield = checkTask.WaitForCompletion();
        yield return customYield;
        ApkAvailabilityStatus result = checkTask.Result;
        switch (result)
        {
            case ApkAvailabilityStatus.SupportedApkTooOld:
                _ShowAndroidToastMessage("Supported apk too old");           
                Session.RequestApkInstallation(false);
                break;
            case ApkAvailabilityStatus.SupportedInstalled:
                _ShowAndroidToastMessage("Supported and installed");
                break;
            case ApkAvailabilityStatus.SupportedNotInstalled:
                _ShowAndroidToastMessage("Supported, not installed, requesting installation");
                Session.RequestApkInstallation(false);
                break;
            case ApkAvailabilityStatus.UnknownChecking:
                _ShowAndroidToastMessage("Unknown Checking");
                break;
            case ApkAvailabilityStatus.UnknownError:
                _ShowAndroidToastMessage("Unknown Error");
                break;
            case ApkAvailabilityStatus.UnknownTimedOut:
                _ShowAndroidToastMessage("Unknown Timed out");
                break;
            case ApkAvailabilityStatus.UnsupportedDeviceNotCapable:
                _ShowAndroidToastMessage("Unsupported Device Not Capable");
                Debug.Log("Unsupported device");
                break;
        }
    }
}`

**Comment by dhaminitinAltran** [comment] 2021-03-26 15:04
Hi using the unity version 20.2.1 and ar core plugin when I tried running the APK on Non supported AR device it returns
the status as  "SupportedNotInstalled" instead of "UnsupportedDeviceNotCapable" on checking the status is there any manifest setting that one needs to or is it a Bug?

**Comment by chaosemer** [comment] 2021-03-29 20:30
@dhaminitinAltran, is your app AR Required or AR Optional? As documented [here](https://developers.google.com/ar/reference/java/com/google/ar/core/ArCoreApk#checkAvailability(android.content.Context)), if an app is AR Required, it will report SupportedNotInstalled when you ask about support. I realize that's the Java docs, not the Unity ones. :)
