### ISSUE TITLE
Build Errors with Unity 2018.2

### ISSUE THREAD

**Issue by RosalineMakar** [google-ar/arcore-unity-sdk#351] opened 2018-08-13 14:07 UTC
Hello,

When Building for Android, After following the steps in: https://developers.google.com/ar/develop/unity/quickstart-android
The Build failed due to the following line in CloudAnchorUIController.cs, line: 85
IPAddressText.text = "My IP Address: "+Network....
The Unity displayed that "Network" is obsolete now, so I fixed this line by removing it "+Network..."
And the build succeeded

Thanks

**Comment by pablisho** [comment] 2018-08-13 14:34
Hi, thanks for the report. This is a duplicate of #197 and will be fixed in the upcoming release.

**Closed by pablisho** 2018-08-13 14:34 UTC
