### ISSUE TITLE
IL2CPP support

### ISSUE THREAD

**Issue by iBicha** [google-ar/arcore-unity-sdk#86] opened 2018-01-25 19:19 UTC
Building for IL2CPP, the session cannot start:

```
01-25 12:14:31.117 20771-20771/com.google.ar.core.examples.unity.helloar E/Unity: NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code.
                                                                                    at GoogleARCoreInternal.NativeApi+ExternApi.ArCoreUnity_resumeSession (GoogleARCoreInternal.EarlyUpdateCallback earlyUpdate) [0x00000] in <filename unknown>:0 
                                                                                    at GoogleARCore.ARCoreSession+<_ResumeSession>c__AnonStorey1.<>m__0 () [0x00000] in <filename unknown>:0 
                                                                                    at GoogleARCore.AsyncTask.OnUIThread () [0x00000] in <filename unknown>:0 
                                                                                    at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
                                                                                    at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <filename unknown>:0 
                                                                                    at UnityEngine.AndroidJavaProxy.Invoke (System.String methodName, System.Object[] args) [0x00000] in <filename unknown>:0 
                                                                                    at UnityEngine._AndroidJNIHelper.InvokeJavaProxyMethod (UnityEngine.AndroidJavaProxy p

```

because `ArCoreUnity_resumeSession` is getting an instance callback .
A fix would be to set the callback to static, and add the `MonoPInvokeCallback` attribute to it

**Comment by chaosemer** [comment] 2018-01-28 19:18
This is a duplicate of #69. We're working on it!

**Closed by chaosemer** 2018-01-28 19:18 UTC

**Comment by sritchie-hookbang** [comment] 2018-02-06 23:37
Can you put a workaround here so we can progress without your fix? I don't understand the proposed fix:
>>A fix would be to set the callback to static, and add the MonoPInvokeCallback attribute to it<<

Can someone explain exactly where to put the static and MonoPInvokeCallback stuff?

Thanks!

**Comment by iBicha** [comment] 2018-02-07 22:15
[Here's a fix](https://github.com/iBicha/arcore-unity-sdk/tree/il2cpp) (I remember someone asking about it)
