### ISSUE TITLE
arcore permissions

### ISSUE THREAD

**Issue by harakiry** [google-ar/arcore-unity-sdk#151] opened 2018-03-26 14:32 UTC
Hello,

I have an issue that the arcore sdk messes with the permissions I set for the android manifest. I just need to add a write_external_storage permission, but it's overwritten by the AndroidPermissionManager script from the LifecycleManager script, adding only the camera permission. Could you please advise how to add multiple permissions based on the arcore scripts or a work around for this. I need to be able to take a screenshot and save it on the device, but without the permission for writing I can't.

Thank you very much

**Comment by pablisho** [comment] 2018-03-27 19:17
Hi, I don't think AndroidPermissionManager is overriding your manifest. If you are targeting android sdk 23 or higher you'll need to request the permissions at runtime and setting them in the manifest won't be enough. For that matter, you can use the AndroidPermissionManager class that ARCore provides with  AndroidPermissionManger.RequestPermission("android.permission.WRITE_EXTERNAL_STORAGE");
Please let me know if this helps.

**Comment by harakiry** [comment] 2018-03-28 10:46
Hello, thank you very much. I managed yesterday to find the the function you mentioned and it worked in the end.
Thank you for your answer.

**Comment by manjia** [comment] 2018-05-28 14:01
I confirm the issue exists and also that using AndroidPermissionManger.RequestPermission("android.permission.WRITE_EXTERNAL_STORAGE") solves the problem.
Still this does not close the issue in my opinion, I see no reason why arcore should overwrite Unity permission, and not being able to trust permissions checked in the Unity editor is a serious threat.

Please fix this issue, the workaround works, but it's just a workaround, not a solution.

**Comment by pablisho** [comment] 2018-05-28 14:15
Hi @manjia, I think ARCore does not override any Unity permission. Did you try reproducing this without ARCore?
I don't think this is  a workaround, this is the proper way to request permission in Android > 23, you must do it at runtime. https://developer.android.com/training/permissions/requesting

**Comment by manjia** [comment] 2018-05-28 14:46
Yeah I sure did, before finding this thread I was debugging the issue myself, so I created a new project and attached this script to a cube:

```
public class SaveFile : MonoBehaviour
{
    void Start()
    {
        string directory = Application.persistentDataPath + "/../../../../TestDirectory/";
        string path = directory + "TestFile.txt";

        DirectoryInfo directoryInfo = new DirectoryInfo(directory);
        if (!directoryInfo.Exists)
        {
            try
            {
                directoryInfo.Create();
            }
            catch (Exception e)
            {
                Debug.Log(e.StackTrace);
            }
        }
        
        try
        {
            File.WriteAllText(path, "write text");
        }
        catch (Exception e)
        {
            Debug.Log(e.StackTrace);
        }
    }

    void Update()
    {
    }
}
```

(the "/../../../../TestDirectory/" part is because I was tring to save on the SDCard root, I know there are better ways to do it but I guarantee that works on the devices I'm using to deploy) 

then I set "Write permission" to "External (SDCard)" in "Player settings -> Other settings" and the WRITE_EXTERNAL_STORAGE permission popup is automatically triggered by Unity on application start

To avoid doubts I also tried to change the "Minimum API Level" switching from Android 4.4 to Android 7.0 (leaving the "Target API Level" to "Automatic (highest installed)"), it doesn't matter which platform I target for "Minimum API Level", if the device I'm deploying to is >= Android 6.0 the runtime permission request popup is always automatically triggered by Unity without the need of triggering it by script, this does not happen anymore after I import ARCore package to my project

I don't know if it's related to the manifest overwrite or not (probably not knowing the runtime permissions system) but it looks like the Unity inspector setting gets somehow overridden

I can share the test project if you need to check it, but it doesn't contain nothing more besides what I just described

**Comment by pablisho** [comment] 2018-05-28 14:53
@manjia Thank you for your explanation. I think this will require more investigation on our side.

**Comment by pablisho** [comment] 2018-07-18 23:45
@manjia Thanks for your report. After looking this, I can say that we decided to do this by design. We want to only request the camera permission once it's necessary (after ARCore Installation through the Play store). As a consequence, the rest of permission also need to be requested at runtime through the [AndroidPermissionsManager](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/AndroidPermissionsManager.cs)

**Closed by pablisho** 2018-07-18 23:45 UTC

**Comment by manjia** [comment] 2018-07-19 12:49
Thank you for clarifying that it's a design choice, but that said, it appers to be a poor design chioce to me for the following reasons:

What you are basically saying is: "if you are using our plugin you should request runtime permissions using our AndroidPermissionsManager class instead of handling them using Unity, like you are use to do in other Unity projects, because we are overriding them all and then we are only applying the Camera request permission", this is confusing to developers as it is currently not specified anywhere and also breaks the Unity build pipeline, since yours is the only one Unity plugin I'm aware of that overrides Unity inspector settings in this invasive way.

There's also a more concrete problem with this behavior: let's say for instance that another plugin that overrides Unity settings and just enables one other permission exists (for instance the write external storage permission), and let's say I'm using them both in the same project: what happens then? Which one "wins" by overriding the other one's permission request? And which one class should I use to request other permissions? because you know, as your library provides an AndroidPermissionsManager expecting the developer to handle permissions with it, nothing prevents the other one library to provide its own AnotherAndroidPermissionsManager class and to expect the developer to handle permission requests using it instead of Unity builtin settings and instead of using your AndroidPermissionsManager.
For this reason this behavior does not appear to be scalable to me.

There are plenty of ways to only request the camera permission once it's necessary different from the one you chose, for instance you should write your IPreprocessBuildWithReport and prompt the developer to enable the camera permission in OnPreprocessBuild, or better to silently enable it there leaving untouched the other checked permissions, another way to do it could be to implement your own Unity menu with a "Check project settings" entry that checks the Camera permission flag in the Unity inspector (like the MixedRealityToolkit does), this would also give you control on other Unity settings different from the permission requests in a non invasive way, if needed.
