### ISSUE TITLE
Image Database destroys project when setting the physical image width (macOS only)

### ISSUE THREAD

**Issue by SebiP2ER** [google-ar/arcore-unity-sdk#385] opened 2018-09-10 15:50 UTC
When I set the width(m) for one of my images in the Augmented Images Database, I'm not able to build the project anymore. The error in the console says "chmod: Demo/Assets/GoogleARCore/CLI/augmented_image_cli_osx: No such file or directory". 

Setting the width back to 0 or reimporting the old version of the database doesn't help. Even reverting the changes via version control didn't help. I had to delete the whole project and set it up from scratch.

My colleague works on Windows and doesn't have the problem. I'm on macOS 10.13.6 with Unity 2018.2.6. I could update to his database with the width set and don't have any errors building the project.

But even with the physical size set, the tracking doesn't seem to improve. When the user doesn't move enough, ARCore still often times thinks the Image is huge and far away or small and closer to the camera... Maybe there is some fundamental problem in the implementation?

**Comment by fredsa** [comment] 2018-09-21 19:42
Couple of questions to help troubleshoot:

1. Does `Demo/Assets/GoogleARCore/CLI/augmented_image_cli_osx` exist?
If not, please try re-imported the ARCore SDK for Unity `*.unitypackge`

2. What are the file permissions on this?
`$ ls -l Demo/Assets/GoogleARCore/CLI/augmented_image_cli_osx`
Expect `r` (read) and `x` (execute) bits to be set.
Sometimes `x` bit can be dropped when checking files into a version control system.

—

Separately for the tracking quality:
1. Are you specifying the image width in meters? e.g. `0.20` for an images that's 20 cm wide
2. ARCore does need some initial movement on part of the user to be able to see the area that contains the image from different perspectives. Generally a circular motion with the phone, same as what you would use to find a plane, is needed.

Regarding #2: note that Agumented Images does not detect images in the way that other image detection algorithms might work. Instead, ARCore looks for feature points in the world, uses multiple frames of stereo perspective to determine which feature points lie in a plane, and then compares those feature point to features points stored in the image database.

Hope that helps.

**Comment by SebiP2ER** [comment] 2018-09-24 20:02
Hi @fredsa,
1. Yes, the "augmented_image_cli_osx" file did exist.
2. I set the permissions to read-, write- and executable for everyone via "chmod 777", which didn't help.
—
3. Yes, we where aware that it's in meters. We set it to `0.19` for 19 cm. But I'm not sure it ever compiled that way on my machine.  A week ago we added a new image with physical size to the database, but after updating my project to the new database the error reappeared. For now we are working without physical sizes.
4. Thats right. We fixed some of the issues by waiting for a detected plane, before searching for the augmented image. We also avoid using prefabs that get instantiated at the anchor position, because those are connected to the anchor forever and slant around like crazy. There seems to be no way of disconnecting the instantiated object from the anchor. What we do instead is leave the object deactivated in the scene and set the position and rotation to that of the anchor after activating it.

One additional note:
- When adding the other image I realized that I'm not able to add any image to the database whatsoever. Even without any physical size, the "Calculating..." dialogue never finishes.

**Comment by nilsk123** [comment] 2018-10-08 12:42
> Hi @fredsa,
> 
> 1. Yes, the "augmented_image_cli_osx" file did exist.
> 2. I set the permissions to read-, write- and executable for everyone via "chmod 777", which didn't help.
>    —
> 3. Yes, we where aware that it's in meters. We set it to `0.19` for 19 cm. But I'm not sure it ever compiled that way on my machine.  A week ago we added a new image with physical size to the database, but after updating my project to the new database the error reappeared. For now we are working without physical sizes.
> 4. Thats right. We fixed some of the issues by waiting for a detected plane, before searching for the augmented image. We also avoid using prefabs that get instantiated at the anchor position, because those are connected to the anchor forever and slant around like crazy. There seems to be no way of disconnecting the instantiated object from the anchor. What we do instead is leave the object deactivated in the scene and set the position and rotation to that of the anchor when the marker gets detected [and is the right size (between 0.19 and 0.20, to make sure the detection was correct)].
> 
> Some additional notes:
> 
> * When adding the other image I realized that I'm not able to add any image to the database whatsoever. Even without any physical size, the "Calculating..." dialogue never finishes.
> * It would be awesome if ARCore could use augmented images with a physical size as fundamental truth, correcting the tracking based on that data, instead of correcting the size of the marker based on inaccurate tracking data.

Had the same problem on Mac OS X, the problem in my case was that the preprocessing buildscript doesn't account for empty spaces in filepaths on mac os x. It is fixed by looking for all occurences of 

`ShellHelper.RunCommand("chmod", "+x " + cliBinaryPath`

and replacing it with

`ShellHelper.RunCommand("chmod", "+x '" + cliBinaryPath + "'"`

There is also an occurence of 

`ShellHelper.RunCommand(cliBinaryPath)`

Which should be

`ShellHelper.RunCommand("'" + cliBinaryPath + "'"`

**Comment by fredsa** [comment] 2018-10-12 23:45
@nilsk123 Thanks for the follow up. You're right about `ShellHelper.RunCommand("chmod", "+x " + cliBinaryPath` needing proper quoting. I reopened #297 and we'll get a fix for that out in an upcoming release.

Note that `ShellHelper.RunCommand(cliBinaryPath)` should be fine without the extra quotes.

**Comment by chaosemer** [comment] 2018-11-21 17:13
This is a duplicate of #297. Resolving.

**Closed by chaosemer** 2018-11-21 17:13 UTC
