### ISSUE TITLE
Vertical Surfaces (Walls) Detection

### ISSUE THREAD

**Issue by TheMachineHere** [google-ar/arcore-unity-sdk#31] opened 2017-10-10 20:28 UTC
Hi,

ARCore can effectively detect horizontal surfaces. I was curious to know whether anyone has found a way to detect vertical surfaces. My app is basically trying to detect various walls and augment objects on walls.

Has anyone found any solution?

Thanks.

**Comment by nathanmartz** [comment] 2017-10-10 20:57
This isn't currently supported but it's a feature request we've received from a number of folks. We'll share more if/when we have a robust solution in ARCore.

**Comment by TheMachineHere** [comment] 2017-10-11 20:26
is there any solution?

**Comment by jimmysoda** [comment] 2017-11-15 22:29
@nathanmartz Has this issue been resolved? I see you also closed the related google-ar/arcore-android-sdk#47 as a dupe of this issue.

**Comment by nathanmartz** [comment] 2017-11-17 06:07
You're right, that's confusing. I'll leave it open since this is a common request but not currently supported.

**Comment by iBicha** [comment] 2017-12-17 07:06
There is actually a hack with very unstable results, but the idea is simple: Regression.
Out of the point cloud, you can pretty much use regression algorithms to see how well can they fit in a plane, Which would lead to not only vertical, but virtually any plane. While this is prone to a huge range of error, the fact that not all points have 100% confidence makes it even worse (And i'm guessing this is probably why it's not a feature in either ARKit nor ARCore for now)

I did an experiment, where I took the closest points to the center of the screen (projected points, that is) got the closest point to the center, added the few closest points to that center (In world space) and applied ransac plane fitting algorithm to try fit these set of points into a plane. The idea was to find the normal of the point I'm looking at. Obviously this would not work at all when looking at a corner, when the central point has no neighbours, but when looking at a framed image (with good visual features, good amount of points) at the wall, I was able to get a very noisy - yet correct, normal vector. I guess the noise is related to how accurate the cloud point is, the number and distance of points (basically the cluster of points that I chose arbitrarily, where it should have based on a solid clustering algo) and finally, a filter is probably needed to get rid of the noise.

I dropped it because it was an overkill for what I was trying to achieve and simply didn't have to the time to dig in more into the idea, but it's definitely a good first lead.

**Comment by sambuev** [comment] 2018-01-15 21:46
I hope they are working on it as well as tracking the specific anchors such as printed-images or QR-codes

**Comment by eisenbruch** [comment] 2018-01-24 14:06
ARKit now has vertical planes and image tracking. I hope ARCore implements the same.

**Comment by brean** [comment] 2018-01-24 23:44
Would be great! I really need this to detect walls for science projects in architecture & construction.

**Comment by juanmajr93** [comment] 2018-02-19 22:24
Is this trouble solved with arcore 2 preview?

**Comment by TakuKobayashi** [comment] 2018-02-20 02:18
I have been able to track the vertical plane and image in arcore 2 preview and current ARKit stable version.
But, I'm sorry. It is difficult to publish the source code.

Instead, I introduce the article and project, these have been the most helpful article and project for vertical planes and image tracking.
(But, written in japanese)

https://qiita.com/rakusan/items/8e3ba031acb31fd7a26c
https://github.com/rakusan/ARKitPlaneDetectionExample

Also, these are implemented by ARKit.
However, you can also get the Cloud Points on ARCore, and after that, do the same things.

**Comment by muizzadeni** [comment] 2018-03-06 16:47
Is this solved with ARcore 1.0?

**Comment by pablisho** [comment] 2018-03-06 17:18
Hi, ARCore 1.0 doesn't support vertical surfaces.

**Comment by pablisho** [comment] 2018-05-09 00:04
Hi, **Vertical Planes** is one of the new features released in [ARCore Unity  SDK v1.2.0](https://github.com/google-ar/arcore-unity-sdk/releases/tag/v1.2.0)

**Closed by pablisho** 2018-05-09 00:04 UTC
Labels: feature request
