### ISSUE TITLE
Session::Resume returning ArStatusErrorSpace::AR_ERROR_CAMERA_NOT_AVAILABLE

### ISSUE THREAD

**Issue by NicolasWipon** [google-ar/arcore-unity-sdk#238] opened 2018-05-31 15:52 UTC
Hi,

I'm working with Unity 2018.1.0f2 and Galaxy S7 (SM-G930F) on Android 7.0.
Sometimes, when I build a project using the "ARCore Device" prefab (with ARCoreSession component on it), I have an issue when I run the app, at the start. The camera feed is  black , and in the logcat, I have these errors : 

_session.cc:451 Session::Resume returning ArStatusErrorSpace::AR_ERROR_CAMERA_NOT_AVAILABLE: 
status.cc:158 ArStatusErrorSpace::AR_ERROR_CAMERA_NOT_AVAILABLE:
ArPresto::ArCore resume failed ArStatus -13
ArPresto::Moving from ArPrestoStatus 102 to 200._

When the camera is working, I have this logcat : 

_session.cc:459 Session::Resume returning OK._

The issue comes randomly.
Did anyone have this issue before ?
Inside Unity, I don't have any feedback from the state of ARSession, so my app doesn't know if the camera is availabled or not. How can I handle this issue ?

Thanks in advance,
Nicolas

**Comment by NicolasWipon** [comment] 2018-06-05 07:55
Hi,
Thanks for your answer.

Unfortunately, I don't have any repro steps because the issue seems to come randomly.

Yes, I'm using "ARCore Instant Preview" to test the app in Unity Editor, and then I build. Sometimes, it works very well, and sometimes I have this issue.

Is there a way, in Unity, to get the return from Session::Resume, so that I could show an error message to the user ?

I have some more informations about the issue : when the issue "AR_ERROR_CAMERA_NOT_AVAILABLE" happens, the camera is locked for all the applications of the smartphone, until we restart the smartphone. Even the "Camera" app doesn't work anymore, and show an error message "Failed to launch camera"

**Comment by pablisho** [comment] 2018-06-07 20:46
Hi, if this happens [Session.Status](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/Session.cs#L39) should be [SessionStatus.FatalError](https://github.com/google-ar/arcore-unity-sdk/blob/master/Assets/GoogleARCore/SDK/Scripts/SessionStatus.cs#L56), you could check that value in the Update() of your controller. Does that help?
Also if you find any pattern how to repro the underlying issue, let me know. My understanding is that is more an Android thing, where only one app can take control of the camera at a time.

**Comment by NicolasWipon** [comment] 2018-06-08 07:56
Hello,
Thank you for your answer, I will check the SessionStatus and tell you if it helps.

However, I figured out the issue comes even when there is no other app launched. Yesterday, I turned on the S7 and I launched only one app (the one I'm working on), and I had this issue. It comes randomly. Maybe it is because of the heat.

**Comment by NicolasWipon** [comment] 2018-06-12 10:22
Hi,

I tested "Session.Status" but it doesn't help. 
When there is the issue with the camera showing a black background, Session.Status is "SessionStatus.LostTracking" instead of "SessionStatus.FatalError".

**Comment by pablisho** [comment] 2018-07-25 16:41
Hi, I cannot reproduce it not being properly informed in Session.Status, I get FatalError when camera is not available. Are you still experiencing this issue? Which version of ARCore are you running?
Regarding the camera not being available in Samsung S7 running Android 7 it could be google-ar/arcore-android-sdk#260.

**Comment by chaosemer** [comment] 2018-09-18 00:00
Closing this issue because we can't reproduce it.

Feel free to reopen if you are still running into this.

**Closed by chaosemer** 2018-09-18 00:00 UTC
Labels: known issue
