### ISSUE TITLE
Unity crashes when resizing game tab while streaming

### ISSUE THREAD

**Issue by geeosp** [google-ar/arcore-unity-sdk#287] opened 2018-07-01 11:49 UTC
Trying to resize the "Game"tab on editor while streaming causes a crash on unity. It freezes and the only solution is to kill the processs.
Using Windows 10 and 2018.1.61f version of editor. Also happens on the LTS version.
I am talking about resizing the tab with a locked aspect ratio

**Comment by pablisho** [comment] 2018-07-02 18:43
Hi, thanks for the report. @gstanlo any ideas?

**Comment by mvgalle** [comment] 2018-07-06 17:12
Same problem here, but with a different version. Using 2018.1.4f1 on Windows 10 1803 17134.112 

Happens when scaling any window element within unity editor. Unity freezes, causing you to close it out and restart it.

**Comment by gstanlo** [comment] 2018-07-09 17:29
Which version of Instant Preview is this on?

**Comment by geeosp** [comment] 2018-07-09 18:29
Arcore 1.2 or 1.3
Instant preview 1.0.8 or 1.0.9
Unity 2017 LTS or later. I tried in various versions , you can get this
behaviour in the most recent one 2018.1.6...
Windows 10 machine

**Comment by fredsa** [comment] 2019-01-11 01:09
Duplicate of #484

**Closed by fredsa** 2019-01-11 01:09 UTC
Labels: Instant Preview, bug
