### ISSUE TITLE
Will "ARCore Supported" unselected interfere the project

### ISSUE THREAD

**Issue by SoftDoggy** [google-ar/arcore-unity-sdk#87] opened 2018-01-28 07:58 UTC
Our group want to realize ARCore in unity5.6, I wonder what's the function of "ARCore Supported" in "XR Settings", what will happen if I don't choose it?
BTY, anyone who has the similar project may know it, is it possible to realize ARCore in unity5.6 if we rewrite the script in unity which is API of ARCore?

**Comment by chaosemer** [comment] 2018-01-28 19:20
Checking "ARCore Supported" tells Unity to do some additional setup that enables the plugin to run. We need some extra hooks into Unity's update loop to property run.

5.6 is not compatible with our plugin, you should update to 2017.3.

**Comment by chaosemer** [comment] 2018-01-28 19:21
(Closing since this is the expected behavior)

**Closed by chaosemer** 2018-01-28 19:21 UTC

**Comment by dariol** [comment] 2018-07-26 07:18
"need some extra hooks into Unity's update loop to property run"

It would help some developers if you could be more specific about what exactly these hooks are especially for those customizing the update loop since the render pipeline is scriptable now in Unity 2018.

**Comment by chaosemer** [comment] 2018-07-26 19:40
The hooks we use in Unity are unrelated to rendering. Some details are that we need clear events for Android's onPause and onResume as well as an update done in line with Unity's internal input updates.
