### ISSUE TITLE
Fresh bugs

### ISSUE THREAD

**Issue by vitorfreire** [google-ar/arcore-unity-sdk#276] opened 2018-06-26 21:43 UTC
I can't even build HelloAR examples because of the following issues. 
I am running Unity 2018.2.0b10 and following all the instructions.

Any easy fix? Thanks!

Assets/GoogleARCore/Examples/CloudAnchor/Scripts/CloudAnchorUIController.cs(85,62): error CS0619: `UnityEngine.Network' is obsolete: `The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.'

Assets/GoogleARCore/Examples/CloudAnchor/Scripts/CloudAnchorUIController.cs(85,62): error CS0619: `UnityEngine.Network.player' is obsolete: `The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.'

Assets/GoogleARCore/Examples/CloudAnchor/Scripts/CloudAnchorUIController.cs(85,69): error CS0619: `UnityEngine.NetworkPlayer.ipAddress' is obsolete: `The legacy networking system has been removed in Unity 2018.2. Use Unity Multiplayer and NetworkIdentity instead.'

**Comment by pablisho** [comment] 2018-06-27 14:08
Hi, this is a duplicate of https://github.com/google-ar/arcore-unity-sdk/issues/197. Unity 2018.2 is still in beta and we are not supporting it yet, we'll be adding support for it in our next releases.
I would recommend you use an stable version of Unity. The versions that ARCore currently support are 2018.1, 2017.4 and 2017.3.

**Closed by pablisho** 2018-06-27 14:08 UTC

**Comment by kromley** [comment] 2018-07-30 19:52
If you delete the CloudAnchor example, the rest works. This should get you going until they get it fixed up.
