### ISSUE TITLE
FFMpeg conflict with this SDK？

### ISSUE THREAD

**Issue by wheat7** [google-ar/arcore-unity-sdk#57] opened 2017-12-18 06:59 UTC
I use FFMpeg to deal with video, and after FFMpeg runned ,APP crash, and Log with:

```
12-15 17:36:36.343 31916-32098/com.xxxxx.xxx A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 32098 (UnityChoreograp)
                                                       
                                                       [ 12-15 17:36:36.344   558:  558 W/         ]
                                                       debuggerd: handling request: pid=31916 uid=10274 gid=10274 tid=32098
```

**Comment by chaosemer** [comment] 2017-12-18 19:14
We haven't seen this before. Can you please share a simplified Unity project that reproduces this issue?

**Comment by fredsa** [comment] 2018-02-06 17:55
Closing as we're unable to reproduce without more information.

**Closed by fredsa** 2018-02-06 17:55 UTC
