### ISSUE TITLE
Unity ARCore 1.5 - ArPrestoAugmentedImageDatabase_create error

### ISSUE THREAD

**Issue by avDOX** [google-ar/arcore-unity-sdk#426] opened 2018-10-21 13:27 UTC
Hello!
I've been having this problem with the new sdk 1.5.

Is there any fix to this? 
I've found this error on augmented image example.

Here is the printscreen of the error.
<img width="904" alt="arcore_imagedatabasecreateerror" src="https://user-images.githubusercontent.com/44340326/47267562-6d672e00-d53d-11e8-8d35-735516e484b8.png">

**Comment by avDOX** [comment] 2018-10-26 10:19
Just to update, I tried everything they said on other issues like the #403.
I tried to buil into my Samsung s7, instant preview etc. nothing works.

**Comment by pablisho** [comment] 2018-10-26 20:13
Hi, I'm closing this as a duplicate of #403, but as a workaround change your platform to android in your build settings, that should remove the editor error.

**Closed by pablisho** 2018-10-26 20:13 UTC
