### ISSUE TITLE
Instant Preview orientation problem.

### ISSUE THREAD

**Issue by SetoKaiba** [google-ar/arcore-unity-sdk#252] opened 2018-06-08 08:29 UTC
Default orientation of my app is landscape left.
If the Instant Preview app is not launched on the phone, the Unity Editor launch the Instant preview app.
And the camera feed is of correct orientation.
If the Instant Preview app is launched, the Unity Editor just try to connect the Instant preview app and use the wrong orientation camera feed. It's rotated and stretched.

**Comment by ls29322** [comment] 2018-06-11 08:54
@SetoKaiba  did you try to change your editor aspect? Maybe if you have Free Aspect the editor gets a little crazy, if you concret the aspect on the same editor maybe it will work. This works for me a couple of times.

**Comment by SetoKaiba** [comment] 2018-06-11 09:23
@ls29322 I use the same resolution from Pixel 2 XL.
case 1:
1. Ensure the Instant Preview App is not launched on the Phone.
2. Run the game in Unity3D.
3. Instant Preview app is launched, the UI is landscape left.
4. The rotation is correct as the game landscape left. And from the log, I can read that the resolution is 1440 * 2720.

case 2:
1. The Instant Preview app is launched on the phone as the previous case, the UI is landscape left.
2. Run the game in Unity3D.
3. Unity connects the phone only, with the launched landscape left UI.
4. The camera feed in Unity3D is rotated and stretched. And from the log, I can read that the resolution is 1440 * 2720.

**Comment by SetoKaiba** [comment] 2018-06-11 09:28
The case is for USB mode only.
I have to close Instant Preview app everytime before I run the game in Unity3D.

**Comment by yosun** [comment] 2018-09-13 18:31
Perhaps just have the Instant Preview app auto-kill itself after each session.

**Comment by fredsa** [comment] 2019-01-10 23:00
Duplicate of #484

**Closed by fredsa** 2019-01-10 23:00 UTC
Labels: Instant Preview, bug

**Comment by fredsa** [comment] 2019-01-10 23:01
Try also resize the game window to be more landscape or more portrait. Either resize the window in the editor, or change the "Free Aspect" drop down to use a resolution that's explicitly landscape or portrait in dimensions.
