### ISSUE TITLE
Google cloud anchors do not resolve on the same device - different session

### ISSUE THREAD

**Issue by Aashwina** [google-ar/arcore-unity-sdk#445] opened 2018-11-10 11:38 UTC

**Comment by Aashwina** [comment] 2018-11-10 11:41
I tried the Google cloud anchor on Unity. The anchors are saved and I get a room id , but they are not resolved. I am fairly sure that I am focusing in the right place when I resolve ( I used a variegated mat so should be clean ). I am on wifi ( both my device and my comp ) so the IP address that I get is like so 192.168.0.x  and I am using this to resolve. Is this right ?  Using Unity 2018.x and ARCore 1.4.

**Comment by chaosemer** [comment] 2018-11-21 17:48
We are improving the Cloud Anchor example in an upcoming release, which should make it much clearer how to do this type of thing.

**Comment by Aashwina** [comment] 2018-11-22 12:45
Thanks Jared . When can we expect the release?

**Comment by small-potatoes** [comment] 2018-12-11 03:03
This issue should now be resolved in the [ARCore 1.6 release](https://github.com/google-ar/arcore-unity-sdk/releases).

**Closed by small-potatoes** 2018-12-11 03:03 UTC
Labels: fixed in upcoming release

**Comment by kushal98** [comment] 2019-01-31 15:16
The issue is still happening in the ARCore 1.6 i am using poco phone and i am facing this issue.

**Comment by RAUNAKKONDIBOYINA** [comment] 2019-02-07 16:53
I am facing the same issue using poco f1. I don't see a resolve option too

**Comment by marklinmao** [comment] 2019-05-07 07:30
I also have the same problem with ARCore 1.8. No resolve button, and it doesn't resolve for the same device...

**Comment by chaosemer** [comment] 2019-10-16 17:49
The sample assumes that you are using Cloud Anchors for a multi-user experience and uses Unity networking to share the cloud anchor ID. If you want to do a persistence-style experience, you will need some other way to share the cloud anchor ID.

See m_CloudAnchorId and CmdSetCloudAnchorId in our example.
