### ISSUE TITLE
Different behaviour between Instant preview and device

### ISSUE THREAD

**Issue by minnes09** [google-ar/arcore-unity-sdk#327] opened 2018-07-28 15:31 UTC
Hello, 
I have noticed a different behaviour between the Instant preview and the application running directly on the device regarding on the movement and positioning of the camera gameobject.
If I change the position/orientation of the ARDevice gameobject by code on the device, every child object is correctly updated. In the editor, the camera only, remains still in the same position/ortientation. I can't move it manually in the scene except if I pause the game, but in the next framework it will return in the previous position.
Looking in the code I have seen that the camera Pose is overrided by the InstanPreview class, maybe that is the reason of this problem. My idea is that it updates the position according to the one of the prvious framework and the movement of the device, without taking in consideration the game object modifications.
Thanks for the help and support.

**Comment by pablisho** [comment] 2018-07-30 18:25
Hi, thanks for the report. I added it to our internal tracker.

**Comment by fredsa** [comment] 2019-01-10 23:03
Duplicate of #484

**Comment by small-potatoes** [comment] 2019-02-15 22:21
This has been fixed in the [ARCore SDK for Unity version 1.7](https://github.com/google-ar/arcore-unity-sdk/releases) release.

**Closed by small-potatoes** 2019-02-15 22:21 UTC
Labels: Instant Preview, bug, duplicate, fixed in upcoming release
