### ISSUE TITLE
Instant Preview: no camera feed on phone (laptop with integrated GPU)

### ISSUE THREAD

**Issue by FUBAR2077** [google-ar/arcore-unity-sdk#399] opened 2018-09-28 04:50 UTC
Hi @pablisho thank you very much for an update! This is perfect timing as from today I will have to test my app a lot :)

The Instant Preview works, but I don't know if this is working correctly - I have preview from phone camera feed in Unity but no camera feed visible on my phone with Instant Preview.

I don't know where exactly to tap when I test my app and the mouse click in Unity does not work
(I have imported 1.5.0 to fresh project). EDIT: Probably examples should also support mouse input from now on, as they support only touch. Some people can be disoriented :p

_Originally posted by @pablisho in https://github.com/google-ar/arcore-unity-sdk/issues/357#issuecomment-425237519_

**Comment by pablisho** [comment] 2018-10-03 13:36
Hi, thanks for the report. The expected behavior is that you see the same on the phone and in the editor windoe. I added it to our internal tracker, but this is likely a device specific issue. Could you please provide information about your device and the version of Unity that you are using?

**Comment by FUBAR2077** [comment] 2018-10-03 14:54
Hi, thanks for response :)

I'm using Samsung Galaxy S7, with current updates etc. with Unity 2018.2.2

The problem still persists but Instant Preview is really helpful even in this shape to understand how Detected Planes work in build :)

**Comment by HolgerDurach** [comment] 2018-10-08 08:41
jfyi, same behavior on my Samsung S8+, device Fingerprint: samsung/dream2ltexx/dream2lte:8.0.0/R16NW/G955FXXU4CRI5:user/release-keys

**Comment by EA1993** [comment] 2018-10-18 09:40
Same problem on Samsung Galaxy Tab S4

**Comment by chaosemer** [comment] 2018-11-14 22:18
I am unable to reproduce this with the phones mentioned on my computer. I believe this is due to the attached computer as HolgerDurach mentioned.

Could you please mention the OS and (if on Windows) graphics card driver version? You can find out the driver version by hitting Win + R and typing in "dxdiag". Then go to the "Display" tab.

For now, I'm going to mark this as a feature request, as I think this is a need to support additional hardware.

**Comment by ashishsfb** [comment] 2018-11-25 21:35
I have the same issue - camera feed not appearing on phone but only in editor though the touch inputs work. 
I have tested on the 
One Plus 6T + my laptop + ARcore 1.5
One Plus 6T + my desktop (with NVIDIA 1080) + ARcore 1.5
Samsung S 7 edge +my laptop + ARcore 1.5
Samsung S 7 edge +my desktop (with NVIDIA 1080) + ARcore 1.5

I think the issue is to do with windows as my One Pus worked fine (the camera feed was there in Instant preview) when connected to a friend's Mac.

**Comment by fredsa** [comment] 2019-01-10 22:51
Duplicate of #484

**Closed by fredsa** 2019-01-10 22:51 UTC
Labels: Instant Preview, feature request
