### ISSUE TITLE
Black screen in built app on V30 and S8

### ISSUE THREAD

**Issue by arisonu123** [google-ar/arcore-unity-sdk#451] opened 2018-11-20 18:24 UTC
I recently upgraded my project's ARCore version from 1.3 to 1.5. After doing so when I run the built app the screen is just black. It never looks for surfaces or anything. I am using Unity version 2018.1.6f1.

**Comment by chaosemer** [comment] 2018-11-21 17:45
Looks like you mistakenly filed this twice. Resolving this one as a duplicate of #452.

**Closed by chaosemer** 2018-11-21 17:45 UTC
